# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go modules - Critical security updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 8
    reviewers:
      - "obsernetics/maintainers"
    assignees:
      - "obsernetics/maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "automerge"
    # Group related updates
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      ebpf:
        patterns:
          - "github.com/cilium/ebpf*"
          - "github.com/cilium/*"
      security:
        patterns:
          - "*security*"
          - "*crypto*"
          - "*tls*"
    ignore:
      # Only ignore pre-release versions
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies with security focus
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 5
    reviewers:
      - "obsernetics/maintainers"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"

  # GitHub Actions - Weekly updates
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "obsernetics/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions-security:
        patterns:
          - "*security*"
          - "*codeql*"
          - "*trivy*"
      actions-core:
        patterns:
          - "*checkout*"
          - "*setup*"
          - "*upload*"