package netpol

import (
	"bytes"
	"fmt"
	"io"
	"strings"

	"sigs.k8s.io/yaml"
)

// Consequence is the sentence that has to be in front of any generated
// NetworkPolicy, because it is the thing a reader will otherwise learn by
// applying one.
//
// A NetworkPolicy is not a filter that is added to whatever the cluster
// already permits. It is a whitelist that switches on the moment it selects a
// pod: every connection it does not name is dropped, including connections
// that were working a second earlier. A generated policy therefore does not
// tighten a workload gradually - it cuts it down to a list derived from one
// learning window and nothing else.
const Consequence = "A NetworkPolicy is allow-only. The moment one selects a pod, every connection in a " +
	"named direction that no rule permits is dropped - including connections that were working a second " +
	"earlier, and connections nobody observed because they happen less often than the learning window is long."

// Blocked counts the workloads that produced no policy.
func (r Result) Blocked() int {
	n := 0
	for _, s := range r.Subjects {
		if s.Blocked() {
			n++
		}
	}
	return n
}

// Report writes the review. It is the default output of the command for a
// reason: the YAML alone is a thing somebody pipes into kubectl, and the whole
// argument of this package is that it should not be piped anywhere unread.
func (r Result) Report(w io.Writer) error {
	b := &strings.Builder{}

	fmt.Fprintf(b, "Generated from observed traffic. Nothing here has been applied.\n\n")
	fmt.Fprintf(b, "%s\n\n", wrapText(Consequence, 78, "  "))

	if len(r.Subjects) == 0 {
		fmt.Fprintf(b, "No learned network baseline to read.\n")
		_, err := io.WriteString(w, b.String())
		return err
	}

	for _, s := range r.Subjects {
		head := s.Key()
		if s.Blocked() {
			fmt.Fprintf(b, "%s\n%s\n", head, strings.Repeat("-", len(head)))
			fmt.Fprintf(b, "  %-16s%s\n", "policy", "none")
		} else {
			fmt.Fprintf(b, "%s\n%s\n", head, strings.Repeat("-", len(head)))
			fmt.Fprintf(b, "  %-16s%s\n", "policy", s.Policy)
			fmt.Fprintf(b, "  %-16s%s\n", "selector", s.Selector.String())
			fmt.Fprintf(b, "  %-16s%d egress, %d ingress\n", "rules", s.EgressRules, s.IngressRules)
		}
		fmt.Fprintf(b, "  %-16s%d learned destination(s), %d written into rules\n",
			"observed", s.Observed, s.Expressed)
		if len(s.Findings) > 0 {
			fmt.Fprintln(b)
		}
		for _, f := range s.Findings {
			fmt.Fprintf(b, "%s\n", wrapText(f.Level.String()+": "+f.Message, 78, "    "))
		}
		fmt.Fprintln(b)
	}

	fmt.Fprintf(b, "%d policy(s) for %d workload(s); %d workload(s) produced none.\n",
		len(r.Policies), len(r.Subjects), r.Blocked())
	fmt.Fprintf(b, "%d finding(s) need a decision before any of this is applied.\n", r.Count(LevelWarn))
	fmt.Fprintf(b, "\nThis command applies nothing. When the review is done:\n  pahlevan netpol -o yaml | kubectl apply -f -\n")

	_, err := io.WriteString(w, b.String())
	return err
}

// YAML renders the manifests, with the consequence as a comment at the top so
// it survives being redirected into a file and read a week later.
func (r Result) YAML() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("# Generated by pahlevan netpol from observed traffic.\n")
	for _, line := range strings.Split(wrapText(Consequence, 74, ""), "\n") {
		b.WriteString("# " + line + "\n")
	}
	b.WriteString("#\n# Review every rule against the report before applying this.\n")

	for i := range r.Policies {
		out, err := yaml.Marshal(&r.Policies[i])
		if err != nil {
			return nil, fmt.Errorf("rendering %s/%s: %w", r.Policies[i].Namespace, r.Policies[i].Name, err)
		}
		b.WriteString("---\n")
		b.Write(out)
	}
	return b.Bytes(), nil
}

// wrapText hard-wraps at width and indents every line, because a terminal is
// where this is read and a 300 column finding is a finding nobody finishes.
func wrapText(s string, width int, indent string) string {
	if width <= len(indent) {
		return indent + s
	}
	limit := width - len(indent)
	var lines []string
	line := ""
	for _, word := range strings.Fields(s) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= limit:
			line += " " + word
		default:
			lines = append(lines, indent+line)
			line = word
		}
	}
	if line != "" {
		lines = append(lines, indent+line)
	}
	if len(lines) == 0 {
		return ""
	}
	return strings.Join(lines, "\n")
}
