---
apiVersion: v1
kind: Namespace
metadata:
  name: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan
    app.kubernetes.io/component: system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pahlevanpolicies.policy.pahlevan.io
  namespace: pahlevan-system
spec:
  group: policy.pahlevan.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
              learning:
                type: object
                properties:
                  enabled:
                    type: boolean
                  duration:
                    type: string
                  autoTransition:
                    type: boolean
              enforcement:
                type: object
                properties:
                  mode:
                    type: string
                    enum: ["monitor", "enforce", "audit"]
                  blockUnknown:
                    type: boolean
          status:
            type: object
            properties:
              phase:
                type: string
              lastUpdate:
                type: string
  scope: Namespaced
  names:
    plural: pahlevanpolicies
    singular: pahlevanpolicy
    kind: PahlevanPolicy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pahlevan-operator
  namespace: pahlevan-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pahlevan-operator
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy.pahlevan.io"]
  resources: ["pahlevanpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["policy.pahlevan.io"]
  resources: ["pahlevanpolicies/status"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pahlevan-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pahlevan-operator
subjects:
- kind: ServiceAccount
  name: pahlevan-operator
  namespace: pahlevan-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pahlevan-operator
  namespace: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pahlevan
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pahlevan
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: pahlevan-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
      - name: operator
        image: ghcr.io/obsernetics/pahlevan:v1.0.0
        imagePullPolicy: Always
        command:
        - /manager
        args:
        - --leader-elect
        - --metrics-bind-address=0.0.0.0:8080
        - --health-probe-bind-address=0.0.0.0:8081
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
            - BPF
            drop:
            - ALL
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: pahlevan-operator-metrics
  namespace: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan
    app.kubernetes.io/component: metrics
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pahlevan
    app.kubernetes.io/component: operator