apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pahlevan-system

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: pahlevan/operator
  newTag: v1.0.0