package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

// A broken page still returns 200. That is what makes these failures expensive
// to find by looking: an unclosed tag swallows the rest of the document into
// the wrong element, the page renders half of itself, and nothing anywhere
// reports an error. So the generated markup is parsed here.

// generatedPages lists every HTML file this generator produces.
func generatedPages(t *testing.T) map[string]string {
	t.Helper()
	site, err := Build(repoRoot)
	if err != nil {
		t.Fatalf("building the site: %v", err)
	}
	out := map[string]string{}
	for path, data := range site.Files {
		if strings.HasSuffix(path, ".html") {
			out[path] = string(data)
		}
	}
	if len(out) == 0 {
		t.Fatal("the generator produced no pages")
	}
	return out
}

// voidElement needs no closing tag, so it must not go on the stack.
var voidElement = map[string]bool{
	"area": true, "base": true, "br": true, "col": true, "embed": true, "hr": true,
	"img": true, "input": true, "link": true, "meta": true, "param": true,
	"source": true, "track": true, "wbr": true,
}

// checkBalanced reports the first tag that is closed out of order or left
// open. html.Parse cannot do this: it is a recovering parser and repairs
// broken markup silently, which is exactly the behaviour that lets a
// generator ship a page with a missing </div> and nobody notice.
func checkBalanced(doc string) string {
	z := html.NewTokenizer(strings.NewReader(doc))
	var stack []string
	for {
		switch z.Next() {
		case html.ErrorToken:
			if len(stack) > 0 {
				return "these elements were never closed: " + strings.Join(stack, ", ")
			}
			return ""
		case html.StartTagToken:
			name, _ := z.TagName()
			if n := string(name); !voidElement[n] {
				stack = append(stack, n)
			}
		case html.EndTagToken:
			name, _ := z.TagName()
			n := string(name)
			if voidElement[n] {
				continue
			}
			if len(stack) == 0 {
				return "</" + n + "> closes an element that was never opened"
			}
			if top := stack[len(stack)-1]; top != n {
				return "</" + n + "> closes out of order; the innermost open element is <" + top + ">"
			}
			stack = stack[:len(stack)-1]
		}
	}
}

func TestGeneratedPagesAreWellFormed(t *testing.T) {
	for path, doc := range generatedPages(t) {
		if problem := checkBalanced(doc); problem != "" {
			t.Errorf("%s is not well-formed: %s", path, problem)
		}
		if _, err := html.Parse(strings.NewReader(doc)); err != nil {
			t.Errorf("%s does not parse: %v", path, err)
		}
	}
}

func TestGeneratedPagesCarryTheSiteChrome(t *testing.T) {
	for path, doc := range generatedPages(t) {
		if path == changelogOut {
			// Hand-written, and only its release region is generated.
			continue
		}
		node, err := html.Parse(strings.NewReader(doc))
		if err != nil {
			t.Fatalf("%s: %v", path, err)
		}
		for _, want := range []atom.Atom{atom.Nav, atom.Main, atom.Footer, atom.Title} {
			if find(node, want) == nil {
				t.Errorf("%s has no <%s>; it would not read as part of the site", path, want)
			}
		}
		if !strings.Contains(doc, `href="../assets/css/main.css?v=`+assetVersion+`"`) {
			t.Errorf("%s does not load the site stylesheet at the current version", path)
		}
		if !strings.Contains(doc, "Generated by hack/sitegen") {
			t.Errorf("%s has no generated-by banner, so the first person to spot a typo will fix the HTML and lose it", path)
		}
	}
}

// The safety property, checked on the published bytes rather than on the
// renderer's promises: the only scripts on a generated page are the two the
// layout loads, and neither comes from a markdown file.
func TestNoScriptComesFromMarkdown(t *testing.T) {
	allowed := map[string]bool{
		"https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-core.min.js":               true,
		"https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/autoloader/prism-autoloader.min.js": true,
		"../assets/js/main.js?v=" + assetVersion:                                                         true,
		"assets/js/main.js?v=" + assetVersion:                                                            true,
	}
	for path, doc := range generatedPages(t) {
		node, err := html.Parse(strings.NewReader(doc))
		if err != nil {
			t.Fatalf("%s: %v", path, err)
		}
		for _, s := range findAll(node, atom.Script) {
			src := attr(s, "src")
			if !allowed[src] {
				t.Errorf("%s loads an unexpected script: %q", path, src)
			}
			if inline := nodeText(s); inline != "" {
				t.Errorf("%s contains an inline script: %q", path, inline)
			}
		}
		// The body of a documentation page is the part that came from
		// markdown. Nothing executable may appear in it at all.
		if body := between(doc, `<article class="doc-body">`, "</article>"); body != "" {
			for _, bad := range []string{"<script", "onerror=", "onclick=", "onload=", "javascript:", "<iframe"} {
				if strings.Contains(strings.ToLower(body), bad) {
					t.Errorf("%s: %q appears in content that came from a markdown file", path, bad)
				}
			}
		}
	}
}

// A link to a page that does not exist is a 404 a reader finds, not a build
// that fails, so it has to be checked here.
func TestEveryInternalLinkResolves(t *testing.T) {
	site, err := Build(repoRoot)
	if err != nil {
		t.Fatal(err)
	}
	published := map[string]bool{}
	for p := range site.Files {
		published[p] = true
	}
	// Files the site already had, which the generated pages link back to.
	for _, p := range []string{"pages/index.html", "pages/changelog.html",
		"pages/assets/css/main.css", "pages/assets/js/main.js", "pages/assets/pahlevan-icon.svg"} {
		published[p] = true
	}

	var missing []string
	for path, data := range site.Files {
		if !strings.HasSuffix(path, ".html") || path == changelogOut {
			continue
		}
		node, err := html.Parse(strings.NewReader(string(data)))
		if err != nil {
			t.Fatal(err)
		}
		dir := filepath.Dir(path)
		for _, ref := range refs(node) {
			if ref == "" || strings.HasPrefix(ref, "#") || strings.Contains(ref, "://") ||
				strings.HasPrefix(ref, "mailto:") {
				continue
			}
			target := ref
			if i := strings.IndexAny(target, "#?"); i >= 0 {
				target = target[:i]
			}
			if target == "" {
				continue
			}
			resolved := filepath.ToSlash(filepath.Clean(filepath.Join(dir, target)))
			if !published[resolved] {
				missing = append(missing, path+" -> "+ref+" (no "+resolved+")")
			}
		}
	}
	sort.Strings(missing)
	if len(missing) > 0 {
		t.Errorf("generated pages link to files the site does not publish:\n  %s", strings.Join(missing, "\n  "))
	}
}

func find(n *html.Node, a atom.Atom) *html.Node {
	if n.Type == html.ElementNode && n.DataAtom == a {
		return n
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		if got := find(c, a); got != nil {
			return got
		}
	}
	return nil
}

func findAll(n *html.Node, a atom.Atom) []*html.Node {
	var out []*html.Node
	if n.Type == html.ElementNode && n.DataAtom == a {
		out = append(out, n)
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		out = append(out, findAll(c, a)...)
	}
	return out
}

func attr(n *html.Node, key string) string {
	for _, a := range n.Attr {
		if a.Key == key {
			return a.Val
		}
	}
	return ""
}

func nodeText(n *html.Node) string {
	var b strings.Builder
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		if c.Type == html.TextNode {
			b.WriteString(c.Data)
		}
	}
	return strings.TrimSpace(b.String())
}

func refs(n *html.Node) []string {
	var out []string
	if n.Type == html.ElementNode {
		for _, key := range []string{"href", "src"} {
			if v := attr(n, key); v != "" {
				out = append(out, v)
			}
		}
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		out = append(out, refs(c)...)
	}
	return out
}

func between(s, open, closing string) string {
	i := strings.Index(s, open)
	if i < 0 {
		return ""
	}
	j := strings.Index(s[i:], closing)
	if j < 0 {
		return ""
	}
	return s[i+len(open) : i+j]
}

// A page whose markup this generator produced has to survive being written and
// read back byte for byte, or -check would report drift on every run.
func TestWriteThenCheckIsClean(t *testing.T) {
	root := scratchRepo(t)
	site, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Apply(root, site, true); err != nil {
		t.Fatal(err)
	}
	again, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	stale, err := Apply(root, again, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(stale) > 0 {
		t.Errorf("-check reported drift immediately after -write: %v", stale)
	}
}

// -check has to fail when a document changes and nobody regenerates. This is
// the review gate.
func TestEditingADocumentMakesCheckFail(t *testing.T) {
	root := scratchRepo(t)
	path := filepath.Join(root, docsDir, "architecture.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(data, []byte("\n## A newly added section\n\nWith a paragraph.\n")...), 0o644); err != nil {
		t.Fatal(err)
	}

	site, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	stale, err := Apply(root, site, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(stale) == 0 {
		t.Fatal("a document was edited and -check said the site was up to date")
	}
}

// The same gate for the changelog: the 3.3.3 failure, at the generator level.
func TestAddingAReleaseMakesCheckFail(t *testing.T) {
	root := scratchRepo(t)
	path := filepath.Join(root, changelogSrc)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	// A new release, inserted where the release process puts one.
	marker := "## [3.3.3]"
	i := strings.Index(string(data), marker)
	if i < 0 {
		t.Fatalf("CHANGELOG.md no longer contains %q; this test is proving nothing", marker)
	}
	added := string(data[:i]) + "## [4.0.0] - 2026-10-01\n\n### Added\n\n- Something that shipped.\n\n" + string(data[i:])
	if err := os.WriteFile(path, []byte(added), 0o644); err != nil {
		t.Fatal(err)
	}

	site, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	stale, err := Apply(root, site, false)
	if err != nil {
		t.Fatal(err)
	}
	if len(stale) == 0 {
		t.Fatal("a release was added to CHANGELOG.md and -check said the site was up to date - this is the 3.3.3 failure")
	}

	if _, err := Apply(root, site, true); err != nil {
		t.Fatal(err)
	}
	page, err := os.ReadFile(filepath.Join(root, changelogOut))
	if err != nil {
		t.Fatal(err)
	}
	releases, err := ParseChangelog(root)
	if err != nil {
		t.Fatal(err)
	}
	if c := auditReleases(releases, string(page)); len(c) > 0 {
		t.Errorf("after regenerating, the page still disagrees with CHANGELOG.md: %v", c)
	}
	if !strings.Contains(string(page), `<h3 class="release-version">4.0.0</h3>`) {
		t.Error("the new release has no article")
	}
}
