package main

import (
	"bytes"
	"html"
	"text/template"
)

// The generated pages have to be indistinguishable from the two hand-written
// ones. A documentation page that arrives with its own header, its own
// typography and no way back to the site reads as a different website that
// happens to share a domain, and the reader stops trusting that the two are
// describing the same thing.
//
// So the header, nav and footer below are copies of pages/index.html's, with
// the link targets adjusted for the pages/docs/ subdirectory, and the pages
// load the same stylesheet rather than one of their own.

// siteURL is the published root. Only used for canonical and social metadata,
// which have to be absolute.
const siteURL = "https://obsernetics.github.io/pahlevan/"

// assetVersion is the cache-busting suffix on the stylesheet and script.
//
// It is a constant here and a literal in the two hand-written pages, and the
// three have to move together: a returning visitor holding a cached main.css
// from before the documentation rules existed would get an unstyled wall of
// text, and would have no reason to hard-refresh.
const assetVersion = "6"

// Layout is everything the shared chrome needs to know about one page.
type Layout struct {
	// Title is the <title>, without the "Pahlevan - " prefix.
	Title string
	// Description is the meta description and the social card text.
	Description string
	// Canonical is the page's path below siteURL, e.g. "docs/architecture.html".
	Canonical string
	// Source names the file this page was generated from, so a reader who
	// views source, or an editor who opens the wrong file, is told where the
	// content actually lives.
	Source string
	// Body is the <main> content. It is generated markup, not user input.
	Body string
	// DocsIsCurrent marks the Docs nav link with aria-current.
	DocsIsCurrent bool
}

// pageTemplate mirrors pages/index.html. Paths are relative to pages/docs/.
//
// text/template rather than html/template: html/template strips HTML comments
// from its output, which would silently delete both the "do not edit" banner
// and the section comments the hand-written pages carry, and it would escape
// the generated body. Every value interpolated into an attribute here is
// escaped explicitly at construction instead - see newLayout.
var pageTemplate = template.Must(template.New("page").Parse(`<!DOCTYPE html>
<!-- Generated by hack/sitegen from {{.Source}}. Do not edit by hand: run "go run ./hack/sitegen -write". -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pahlevan - {{.Title}}</title>
    <meta name="description" content="{{.Description}}">
    <meta name="theme-color" content="#0b1020">

    <!-- Open Graph Meta Tags -->
    <meta property="og:title" content="Pahlevan - {{.Title}}">
    <meta property="og:description" content="{{.Description}}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="` + siteURL + `{{.Canonical}}">
    <meta property="og:image" content="` + siteURL + `assets/demo.gif">

    <!-- Twitter Card Meta Tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Pahlevan - {{.Title}}">
    <meta name="twitter:description" content="{{.Description}}">
    <meta name="twitter:image" content="` + siteURL + `assets/demo.gif">

    <link rel="canonical" href="` + siteURL + `{{.Canonical}}">
    <link rel="icon" type="image/svg+xml" href="../assets/pahlevan-icon.svg">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="../assets/css/main.css?v=` + assetVersion + `">

    <!-- Prism.js for code highlighting -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css" rel="stylesheet">
</head>
<body>
    <a class="skip-link" href="#main">Skip to content</a>

    <nav class="navbar">
        <div class="container">
            <a href="../index.html" class="nav-brand">
                <img src="../assets/pahlevan-icon.svg" alt="" class="nav-logo" aria-hidden="true">
                <span>Pahlevan</span>
            </a>
            <div class="nav-links">
                <a href="../index.html#why" class="nav-link">Why</a>
                <a href="../index.html#architecture" class="nav-link">Architecture</a>
                <a href="../index.html#benchmarks" class="nav-link">Benchmarks</a>
                <a href="../index.html#install" class="nav-link">Install</a>
                <a href="index.html" class="nav-link"{{if .DocsIsCurrent}} aria-current="page"{{end}}>Docs</a>
                <a href="../changelog.html" class="nav-link">Changelog</a>
                <a href="` + repoURL + `" class="nav-link nav-github" target="_blank" rel="noopener">GitHub &#8599;</a>
            </div>
            <button class="nav-toggle" aria-label="Toggle navigation" aria-expanded="false">
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </nav>

    <main id="main">
{{.Body}}
    </main>

    <footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-brand">
                    <a href="../index.html" class="nav-brand">
                        <img src="../assets/pahlevan-icon.svg" alt="" class="footer-logo" aria-hidden="true">
                        <span>Pahlevan</span>
                    </a>
                    <p>eBPF-powered runtime security for Kubernetes. Self-learning workload baselines, enforced in-kernel - no hand-written rules.</p>
                </div>
                <div class="footer-links">
                    <div class="footer-section">
                        <h4>Project</h4>
                        <a href="` + repoURL + `" target="_blank" rel="noopener">GitHub</a>
                        <a href="` + repoURL + `/releases" target="_blank" rel="noopener">Releases</a>
                        <a href="../changelog.html">Changelog</a>
                        <a href="` + blobURL + `LICENSE" target="_blank" rel="noopener">License (Apache 2.0)</a>
                    </div>
                    <div class="footer-section">
                        <h4>Docs</h4>
                        <a href="index.html">All documentation</a>
                        <a href="architecture.html">Architecture</a>
                        <a href="quick-start.html">Quick start</a>
                        <a href="packages.html">Packages</a>
                    </div>
                    <div class="footer-section">
                        <h4>Community</h4>
                        <a href="` + repoURL + `/issues" target="_blank" rel="noopener">Issues</a>
                        <a href="` + repoURL + `/discussions" target="_blank" rel="noopener">Discussions</a>
                        <a href="` + blobURL + `CONTRIBUTING.md" target="_blank" rel="noopener">Contributing</a>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; <span id="year">2026</span> Pahlevan &middot; Licensed under Apache 2.0</p>
                <p class="footer-tagline">Learn the baseline. Block the deviation.</p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-core.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/plugins/autoloader/prism-autoloader.min.js"></script>
    <script src="../assets/js/main.js?v=` + assetVersion + `"></script>
</body>
</html>
`))

// newLayout escapes everything that lands in an attribute or in text.
//
// The title and description come out of a markdown file anybody can edit. An
// unescaped quote in a heading would close the content attribute of a meta tag
// and put the rest of the sentence into the markup.
func newLayout(title, description, canonical, source, body string) Layout {
	return Layout{
		Title:       html.EscapeString(title),
		Description: html.EscapeString(description),
		Canonical:   html.EscapeString(canonical),
		Source:      html.EscapeString(source),
		Body:        body,
	}
}

// render wraps a body in the site chrome.
func (l Layout) render() ([]byte, error) {
	var buf bytes.Buffer
	if err := pageTemplate.Execute(&buf, l); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
