{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pahlevan-operator.serviceMonitorName" . }}
  namespace: {{ include "pahlevan-operator.namespace" . }}
  labels:
    {{- include "pahlevan-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pahlevan-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    path: {{ .Values.metrics.path }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    honorLabels: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'pahlevan_.*'
      action: keep
{{- end }}

{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "pahlevan-operator.prometheusRuleName" . }}
  namespace: {{ include "pahlevan-operator.namespace" . }}
  labels:
    {{- include "pahlevan-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: pahlevan-operator.rules
    rules:
    # Operator health alerts
    - alert: PahlevanOperatorDown
      expr: up{job="pahlevan-operator-metrics"} == 0
      for: 5m
      labels:
        severity: critical
        component: pahlevan-operator
      annotations:
        summary: "Pahlevan Operator is down"
        description: "Pahlevan Operator has been down for more than 5 minutes."

    - alert: PahlevanOperatorRestartingTooOften
      expr: increase(process_start_time_seconds{job="pahlevan-operator-metrics"}[1h]) > 3
      for: 5m
      labels:
        severity: warning
        component: pahlevan-operator
      annotations:
        summary: "Pahlevan Operator restarting too often"
        description: "Pahlevan Operator has restarted {{ "{{ $value }}" }} times in the last hour."

    # Policy enforcement alerts
    - alert: HighPolicyViolationRate
      expr: rate(pahlevan_policy_violations_total[5m]) > 10
      for: 2m
      labels:
        severity: warning
        component: policy-enforcement
      annotations:
        summary: "High policy violation rate"
        description: "Policy violation rate is {{ "{{ $value }}" }} violations per second."

    - alert: PolicyEnforcementFailed
      expr: increase(pahlevan_enforcement_failures_total[5m]) > 0
      for: 1m
      labels:
        severity: critical
        component: policy-enforcement
      annotations:
        summary: "Policy enforcement failures detected"
        description: "{{ "{{ $value }}" }} policy enforcement failures in the last 5 minutes."

    # Self-healing alerts
    - alert: SelfHealingActionTriggered
      expr: increase(pahlevan_self_healing_actions_total[10m]) > 0
      for: 0m
      labels:
        severity: warning
        component: self-healing
      annotations:
        summary: "Self-healing action triggered"
        description: "Self-healing action triggered: {{ "{{ $labels.action }}" }}. Container: {{ "{{ $labels.container_id }}" }}"

    - alert: FrequentSelfHealingActions
      expr: rate(pahlevan_self_healing_actions_total[1h]) > 5
      for: 10m
      labels:
        severity: critical
        component: self-healing
      annotations:
        summary: "Frequent self-healing actions"
        description: "Self-healing rate is {{ "{{ $value }}" }} actions per second over the last hour."

    # Learning progress alerts
    - alert: LearningStuck
      expr: |
        (
          pahlevan_learning_progress_ratio < 0.5
          and
          time() - pahlevan_learning_start_time > 3600
        )
      for: 5m
      labels:
        severity: warning
        component: learning
      annotations:
        summary: "Learning progress appears stuck"
        description: "Learning progress for policy {{ "{{ $labels.policy_name }}" }} is only {{ "{{ $value }}" }}% after more than 1 hour."

    - alert: LowLearningQuality
      expr: pahlevan_baseline_quality_score < 0.7
      for: 5m
      labels:
        severity: warning
        component: learning
      annotations:
        summary: "Low learning quality detected"
        description: "Baseline quality score for policy {{ "{{ $labels.policy_name }}" }} is {{ "{{ $value }}" }}, which is below the recommended threshold."

    # Attack surface alerts
    - alert: HighAttackSurfaceRiskScore
      expr: pahlevan_attack_surface_risk_score > 80
      for: 2m
      labels:
        severity: warning
        component: attack-surface
      annotations:
        summary: "High attack surface risk score"
        description: "Attack surface risk score for {{ "{{ $labels.namespace }}" }}/{{ "{{ $labels.workload }}" }} is {{ "{{ $value }}" }}."

    - alert: UnusualSyscallActivity
      expr: |
        (
          increase(pahlevan_syscalls_total[5m])
          >
          on(container_id) (
            avg_over_time(pahlevan_syscalls_total[1h] offset 1h) * 3
          )
        )
      for: 2m
      labels:
        severity: warning
        component: syscall-monitoring
      annotations:
        summary: "Unusual syscall activity detected"
        description: "Container {{ "{{ $labels.container_id }}" }} has {{ "{{ $value }}" }} syscalls in 5 minutes, which is 3x higher than normal."

    # eBPF monitoring alerts
    - alert: EBPFProgramLoadFailed
      expr: increase(pahlevan_ebpf_program_load_failures_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
        component: ebpf
      annotations:
        summary: "eBPF program load failure"
        description: "Failed to load eBPF program: {{ "{{ $labels.program_name }}" }}. Error: {{ "{{ $labels.error }}" }}"

    - alert: EBPFEventBufferFull
      expr: pahlevan_ebpf_event_buffer_usage > 0.9
      for: 1m
      labels:
        severity: warning
        component: ebpf
      annotations:
        summary: "eBPF event buffer near capacity"
        description: "eBPF event buffer usage is {{ "{{ $value }}" }}% for program {{ "{{ $labels.program_name }}" }}."

    # Custom rules from values
    {{- with .Values.metrics.prometheusRule.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}