{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pahlevan.fullname" . }}-agent-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pahlevan.labels" . | nindent 4 }}
    app.kubernetes.io/name: pahlevan-agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pahlevan-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pahlevan.fullname" . }}-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pahlevan.labels" . | nindent 4 }}
    app.kubernetes.io/name: pahlevan-operator
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pahlevan-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
