{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pahlevan.agentServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pahlevan.labels" . | nindent 4 }}
    app.kubernetes.io/name: pahlevan-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pahlevan.operatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pahlevan.labels" . | nindent 4 }}
    app.kubernetes.io/name: pahlevan-operator
{{- end }}
