{{- if .Values.webhooks.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pahlevan-operator.webhookCertSecretName" . }}
  namespace: {{ include "pahlevan-operator.namespace" . }}
  labels:
    {{- include "pahlevan-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
type: kubernetes.io/tls
data:
  {{- include "pahlevan-operator.webhookCerts" . | nindent 2 }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: {{ include "pahlevan-operator.validatingWebhookName" . }}
  labels:
    {{- include "pahlevan-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
webhooks:
- name: vpahlevanpolicy.kb.io
  clientConfig:
    service:
      name: {{ include "pahlevan-operator.webhookServiceName" . }}
      namespace: {{ include "pahlevan-operator.namespace" . }}
      path: /validate-policy-pahlevan-io-v1alpha1-pahlevanpolicy
    {{- if .Values.webhooks.certificate.ca }}
    caBundle: {{ include "pahlevan-operator.caBundle" . }}
    {{- end }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - policy.pahlevan.io
    apiVersions:
    - v1alpha1
    resources:
    - pahlevanpolicies
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  failurePolicy: {{ .Values.webhooks.failurePolicy }}
  timeoutSeconds: {{ .Values.webhooks.timeoutSeconds }}
  {{- with .Values.webhooks.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.webhooks.objectSelector }}
  objectSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: {{ include "pahlevan-operator.mutatingWebhookName" . }}
  labels:
    {{- include "pahlevan-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
webhooks:
- name: mpahlevanpolicy.kb.io
  clientConfig:
    service:
      name: {{ include "pahlevan-operator.webhookServiceName" . }}
      namespace: {{ include "pahlevan-operator.namespace" . }}
      path: /mutate-policy-pahlevan-io-v1alpha1-pahlevanpolicy
    {{- if .Values.webhooks.certificate.ca }}
    caBundle: {{ include "pahlevan-operator.caBundle" . }}
    {{- end }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - policy.pahlevan.io
    apiVersions:
    - v1alpha1
    resources:
    - pahlevanpolicies
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  failurePolicy: {{ .Values.webhooks.failurePolicy }}
  timeoutSeconds: {{ .Values.webhooks.timeoutSeconds }}
  {{- with .Values.webhooks.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.webhooks.objectSelector }}
  objectSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- if .Values.webhooks.certificate.autoGenerate }}
---
# Job to update webhook CA bundle
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pahlevan-operator.fullname" . }}-webhook-patch
  namespace: {{ include "pahlevan-operator.namespace" . }}
  labels:
    {{- include "pahlevan-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "pahlevan-operator.fullname" . }}-webhook-patch
      labels:
        {{- include "pahlevan-operator.labels" . | nindent 8 }}
        app.kubernetes.io/component: webhook-patch
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "pahlevan-operator.serviceAccountName" . }}
      containers:
      - name: patch
        image: kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e

          # Get the CA bundle from the secret
          CA_BUNDLE=$(kubectl get secret {{ include "pahlevan-operator.webhookCertSecretName" . }} \
            -n {{ include "pahlevan-operator.namespace" . }} \
            -o jsonpath='{.data.ca\.crt}')

          # Patch the validating webhook
          kubectl patch validatingadmissionwebhook {{ include "pahlevan-operator.validatingWebhookName" . }} \
            --type='json' \
            -p="[{'op': 'replace', 'path': '/webhooks/0/clientConfig/caBundle', 'value': '${CA_BUNDLE}'}]"

          # Patch the mutating webhook
          kubectl patch mutatingadmissionwebhook {{ include "pahlevan-operator.mutatingWebhookName" . }} \
            --type='json' \
            -p="[{'op': 'replace', 'path': '/webhooks/0/clientConfig/caBundle', 'value': '${CA_BUNDLE}'}]"

          echo "Webhook CA bundle updated successfully"
{{- end }}

{{- end }}