// Package profilesync materialises every learned seccomp profile onto every
// node.
//
// A profile is generated by the agent on the node where the container happened
// to run, which makes it useless for the thing it exists for. A pod's
// seccompProfile is resolved by the kubelet at admission, and a rollout can
// place the pod anywhere; referencing a profile that exists on one node out of
// fifty means the pod fails to start on the other forty-nine. That, and not the
// admission mechanics, is what kept the seccomp loop open.
//
// The fix needs no new API object. ContainerProfile already carries the learned
// syscall set and is replicated to every node by the API server, and profile
// generation is deterministic given that set plus the governing policy's
// syscall lists. So each agent regenerates every profile locally. The source of
// truth is the CR; the files are a derived cache that any node can rebuild.
package profilesync

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-logr/logr"
	"sigs.k8s.io/controller-runtime/pkg/client"

	policyv1alpha1 "github.com/obsernetics/pahlevan/pkg/apis/policy/v1alpha1"
	"github.com/obsernetics/pahlevan/pkg/seccomp"
)

// filePrefix marks the files this syncer owns. Anything in the directory
// without it is left alone: the directory may be shared, and deleting a file
// somebody else put there would be worse than leaving a stale one.
const filePrefix = "pahlevan-"

// Syncer writes the cluster's learned profiles into this node's seccomp
// directory.
type Syncer struct {
	Client client.Client
	Log    logr.Logger

	// Dir is where profiles are written. It must be under the kubelet's
	// seccomp root or the kubelet cannot resolve what is written there.
	Dir string

	// Namespace limits the sync to one namespace. Empty syncs the cluster,
	// which is the useful default: a pod can be scheduled onto this node from
	// any namespace.
	Namespace string
}

// Result reports what one pass did, so the caller can log something meaningful
// rather than "sync ok".
type Result struct {
	Written int
	Removed int
	Skipped int
	Errors  int
}

// ProfileFileName is the file a container's profile is written to. It is
// derived from the profile object rather than the pod UID so that the name a
// remote node computes matches the one the owning node reported.
func ProfileFileName(p *policyv1alpha1.ContainerProfile) string {
	name := p.Spec.PodName
	if name == "" {
		name = p.Name
	}
	return filePrefix + p.Namespace + "-" + name + ".json"
}

// Sync makes this node's seccomp directory match the cluster's learned
// profiles.
//
// Errors on individual profiles are counted and logged rather than returned:
// one malformed profile must not stop the other forty-nine from being
// materialised, since the consequence of a missing file is a pod that will not
// start.
func (s *Syncer) Sync(ctx context.Context) (Result, error) {
	var res Result
	if s.Dir == "" {
		return res, nil
	}

	var list policyv1alpha1.ContainerProfileList
	var opts []client.ListOption
	if s.Namespace != "" {
		opts = append(opts, client.InNamespace(s.Namespace))
	}
	if err := s.Client.List(ctx, &list, opts...); err != nil {
		return res, fmt.Errorf("listing container profiles: %w", err)
	}

	if err := os.MkdirAll(s.Dir, 0o755); err != nil {
		return res, fmt.Errorf("creating %s: %w", s.Dir, err)
	}

	// Policies are fetched once per name rather than once per profile: a
	// thousand containers usually share a handful of policies.
	policies := map[string]*policyv1alpha1.PahlevanPolicy{}

	want := make(map[string]struct{}, len(list.Items))
	for i := range list.Items {
		p := &list.Items[i]
		if len(p.Status.LearnedSyscalls) == 0 {
			// Nothing learned yet. Writing an empty default-deny profile would
			// be a profile that kills the workload on the next rollout.
			res.Skipped++
			continue
		}

		data, err := s.render(ctx, p, policies)
		if err != nil {
			res.Errors++
			s.Log.V(1).Info("could not render profile",
				"profile", p.Namespace+"/"+p.Name, "error", err.Error())
			continue
		}

		name := ProfileFileName(p)
		want[name] = struct{}{}
		changed, err := writeIfChanged(filepath.Join(s.Dir, name), data)
		if err != nil {
			res.Errors++
			s.Log.Error(err, "could not write profile", "profile", p.Namespace+"/"+p.Name)
			continue
		}
		if changed {
			res.Written++
		}
	}

	removed, err := s.prune(want)
	res.Removed = removed
	if err != nil {
		res.Errors++
		s.Log.V(1).Info("could not prune stale profiles", "error", err.Error())
	}
	return res, nil
}

// render regenerates the profile for one container.
//
// Generation is deterministic given the learned set and the policy's syscall
// lists, which is what lets a node that never ran the container produce a byte
// identical file.
func (s *Syncer) render(ctx context.Context, p *policyv1alpha1.ContainerProfile,
	cache map[string]*policyv1alpha1.PahlevanPolicy,
) ([]byte, error) {
	var allow, deny []string
	if ref := p.Spec.PolicyRef; ref != "" {
		key := p.Namespace + "/" + ref
		pol, seen := cache[key]
		if !seen {
			var fetched policyv1alpha1.PahlevanPolicy
			if err := s.Client.Get(ctx, client.ObjectKey{Namespace: p.Namespace, Name: ref}, &fetched); err == nil {
				pol = &fetched
			}
			// A miss is cached as nil: a deleted policy should not be re-fetched
			// once per profile on every pass.
			cache[key] = pol
		}
		if pol != nil && pol.Spec.SyscallPolicy != nil {
			allow = pol.Spec.SyscallPolicy.AllowedSyscalls
			deny = pol.Spec.SyscallPolicy.DeniedSyscalls
		}
	}

	nums := make([]uint64, 0, len(p.Status.LearnedSyscalls))
	for _, nr := range p.Status.LearnedSyscalls {
		if nr < 0 {
			continue
		}
		nums = append(nums, uint64(nr))
	}

	prof, _ := seccomp.GenerateWithOverrides(nums, allow, deny)
	return prof.JSON()
}

// prune removes files this syncer owns that no longer correspond to a profile.
//
// A stale profile is not merely untidy: a workload can keep referencing it
// indefinitely, so the node would go on enforcing a baseline the cluster has
// forgotten.
func (s *Syncer) prune(want map[string]struct{}) (int, error) {
	entries, err := os.ReadDir(s.Dir)
	if err != nil {
		return 0, err
	}
	removed := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasPrefix(e.Name(), filePrefix) {
			continue
		}
		if _, keep := want[e.Name()]; keep {
			continue
		}
		if err := os.Remove(filepath.Join(s.Dir, e.Name())); err != nil && !os.IsNotExist(err) {
			return removed, err
		}
		removed++
	}
	return removed, nil
}

// writeIfChanged avoids rewriting a file whose content already matches.
//
// The sync runs on a timer, and rewriting every profile every tick would churn
// the node's disk and, worse, briefly truncate a file the kubelet might be
// reading during a pod start. The write is atomic via rename for the same
// reason.
func writeIfChanged(path string, data []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(data) {
		return false, nil
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return false, err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return false, err
	}
	return true, nil
}
