/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package commands

import (
	"bytes"
	"context"
	"errors"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	appsv1 "k8s.io/api/apps/v1"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	crclient "sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/client/interceptor"

	policyv1alpha1 "github.com/obsernetics/pahlevan/pkg/apis/policy/v1alpha1"
	"github.com/obsernetics/pahlevan/pkg/cli"
	"github.com/obsernetics/pahlevan/pkg/cycle"
	"github.com/obsernetics/pahlevan/pkg/netpol"
)

// A namespace with two workloads whose labels tell them apart, one learned
// baseline, and the pods to check any generated selector against.

func netpolPod(ns, name, ip, owner string, labels map[string]string) *corev1.Pod {
	p := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{Namespace: ns, Name: name, Labels: labels},
		Status:     corev1.PodStatus{PodIP: ip},
	}
	if owner != "" {
		yes := true
		p.OwnerReferences = []metav1.OwnerReference{{
			APIVersion: "apps/v1", Kind: "ReplicaSet", Name: owner, Controller: &yes,
		}}
	}
	return p
}

func netpolReplicaSet(ns, name, deployment string) *appsv1.ReplicaSet {
	yes := true
	return &appsv1.ReplicaSet{ObjectMeta: metav1.ObjectMeta{
		Namespace: ns, Name: name,
		OwnerReferences: []metav1.OwnerReference{{
			APIVersion: "apps/v1", Kind: "Deployment", Name: deployment, Controller: &yes,
		}},
	}}
}

func netpolProfile(ns, name, pod, kind, workload string, dests ...string) *policyv1alpha1.ContainerProfile {
	return &policyv1alpha1.ContainerProfile{
		ObjectMeta: metav1.ObjectMeta{Namespace: ns, Name: name},
		Spec: policyv1alpha1.ContainerProfileSpec{
			Namespace: ns,
			PodName:   pod,
			Workload:  &policyv1alpha1.WorkloadReference{Kind: kind, Name: workload, Namespace: ns},
		},
		Status: policyv1alpha1.ContainerProfileStatus{
			Phase:                      "Enforcing",
			LearnedNetworkDestinations: dests,
		},
	}
}

// netpolCluster is one web Deployment talking to one api Deployment.
func netpolCluster() []crclient.Object {
	return []crclient.Object{
		netpolPod("prod", "web-abc-1", "10.0.0.1", "web-abc", map[string]string{"app": "web"}),
		netpolPod("prod", "api-def-1", "10.0.1.1", "api-def", map[string]string{"app": "api"}),
		netpolReplicaSet("prod", "web-abc", "web"),
		netpolReplicaSet("prod", "api-def", "api"),
		netpolProfile("prod", "web-abc-1-main", "web-abc-1", "Deployment", "web", "10.0.1.1:8080", "10.0.1.1:53"),
	}
}

func runNetpol(t *testing.T, args ...string) (string, error) {
	t.Helper()
	cmd := NewNetpolCommand()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs(args)
	err := cmd.Execute()
	return out.String(), err
}

func TestNetpolCommandGeneratesFromTheBaseline(t *testing.T) {
	installFakeClients(t, netpolCluster()...)

	out, err := runNetpol(t, "-n", "prod")
	require.NoError(t, err)

	assert.Contains(t, out, "Nothing here has been applied")
	assert.Contains(t, out, "allow-only")
	assert.Contains(t, out, "prod/Deployment/web")
	assert.Contains(t, out, "pahlevan-deployment-web")
	assert.Contains(t, out, "app=web")
	assert.Contains(t, out, "This command applies nothing")
}

func TestNetpolCommandYAMLIsApplyable(t *testing.T) {
	installFakeClients(t, netpolCluster()...)

	out, err := runNetpol(t, "-n", "prod", "-o", "yaml")
	require.NoError(t, err)

	assert.Contains(t, out, "apiVersion: networking.k8s.io/v1")
	assert.Contains(t, out, "kind: NetworkPolicy")
	assert.Contains(t, out, "name: pahlevan-deployment-web")
	assert.Contains(t, out, "app: api", "the observed peer became a selector over the api workload")
	assert.Contains(t, out, "# Generated by pahlevan netpol", "the consequence survives being redirected to a file")
}

func TestNetpolCommandJSONCarriesTheFindings(t *testing.T) {
	installFakeClients(t, netpolCluster()...)

	out, err := runNetpol(t, "-n", "prod", "-o", "json")
	require.NoError(t, err)

	assert.Contains(t, out, `"workload": "Deployment/web"`)
	assert.Contains(t, out, `"selector": "app=web"`)
	assert.Contains(t, out, `"findings"`)
}

func TestNetpolCommandRefusesASelectorWiderThanTheEvidence(t *testing.T) {
	// A debug deployment shares the app label. Any selector derived from the
	// watched pods also selects it, and nobody watched it.
	installFakeClients(t,
		netpolPod("prod", "api-def-1", "10.0.1.1", "api-def", map[string]string{"app": "api"}),
		netpolPod("prod", "dbg-ghi-1", "10.0.1.9", "dbg-ghi", map[string]string{"app": "api", "debug": "1"}),
		netpolReplicaSet("prod", "api-def", "api"),
		netpolReplicaSet("prod", "dbg-ghi", "api-debug"),
		netpolProfile("prod", "api-def-1-main", "api-def-1", "Deployment", "api", "203.0.113.7:443"),
	)

	out, err := runNetpol(t, "-n", "prod")
	require.NoError(t, err)

	assert.Contains(t, out, "policy          none")
	assert.Contains(t, out, "prod/dbg-ghi-1")
	assert.Contains(t, out, "never observed")
	assert.NotContains(t, out, "apiVersion: networking.k8s.io/v1")
}

func TestNetpolCommandDiffsAgainstWhatIsAlreadyThere(t *testing.T) {
	objs := netpolCluster()
	objs = append(objs, &networkingv1.NetworkPolicy{
		ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "pahlevan-deployment-web", ResourceVersion: "999"},
		Spec: networkingv1.NetworkPolicySpec{
			PodSelector: metav1.LabelSelector{MatchLabels: map[string]string{"app": "something-else"}},
		},
	})
	installFakeClients(t, objs...)

	out, err := runNetpol(t, "-n", "prod", "--diff")
	require.NoError(t, err)

	assert.Contains(t, out, "Against the NetworkPolicies already in the cluster")
	assert.Contains(t, out, "already exists and would be replaced")
	assert.Contains(t, out, "- ", "the displaced rules are shown, not only the new ones")
	assert.NotContains(t, out, "999", "a resourceVersion is not a difference in what the policy says")
}

func TestNetpolCommandDiffCallsANewPolicyNew(t *testing.T) {
	installFakeClients(t, netpolCluster()...)

	out, err := runNetpol(t, "-n", "prod", "--diff")
	require.NoError(t, err)
	assert.Contains(t, out, "prod/pahlevan-deployment-web is new")
}

func TestNetpolCommandDirections(t *testing.T) {
	installFakeClients(t, netpolCluster()...)

	egressOnly, err := runNetpol(t, "-n", "prod", "--direction", "egress", "-o", "yaml")
	require.NoError(t, err)
	assert.Contains(t, egressOnly, "- Egress")
	assert.NotContains(t, egressOnly, "- Ingress")

	_, err = runNetpol(t, "-n", "prod", "--direction", "sideways")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "expected one of both, egress, ingress")
}

func TestNetpolCommandRejectsAnUnknownOutputFormat(t *testing.T) {
	installFakeClients(t, netpolCluster()...)
	_, err := runNetpol(t, "-o", "toml")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "invalid --output")
}

func TestNetpolCommandNeedsACluster(t *testing.T) {
	prevK8s, prevReady := k8sClient, clientsReady
	k8sClient, clientsReady = nil, false
	t.Cleanup(func() { k8sClient, clientsReady = prevK8s, prevReady })

	_, err := runNetpol(t)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not initialized")
}

func TestNetpolCommandSaysWhyItIsEmpty(t *testing.T) {
	// "No resources found" sends somebody looking in the wrong place. The
	// reason a baseline is missing is that nothing has finished learning.
	installFakeClients(t)

	out, err := runNetpol(t, "-n", "prod")
	require.NoError(t, err)
	assert.Contains(t, out, "No learned network baseline to read")
	assert.Contains(t, out, "pahlevan profile list -A")
}

func TestNetpolCommandReadsEveryNamespace(t *testing.T) {
	objs := netpolCluster()
	objs = append(objs,
		netpolPod("staging", "web-xyz-1", "10.1.0.1", "web-xyz", map[string]string{"app": "web"}),
		netpolReplicaSet("staging", "web-xyz", "web"),
		netpolProfile("staging", "web-xyz-1-main", "web-xyz-1", "Deployment", "web", "1.1.1.1:53"),
	)
	installFakeClients(t, objs...)

	out, err := runNetpol(t, "-A")
	require.NoError(t, err)
	assert.Contains(t, out, "prod/Deployment/web")
	assert.Contains(t, out, "staging/Deployment/web")
}

func TestNetpolCommandUsesTheNamePrefix(t *testing.T) {
	installFakeClients(t, netpolCluster()...)
	out, err := runNetpol(t, "-n", "prod", "--name-prefix", "reviewed-", "-o", "yaml")
	require.NoError(t, err)
	assert.Contains(t, out, "name: reviewed-deployment-web")
}

// -------------------------------------------------------- collection units

func TestParseDestination(t *testing.T) {
	d, ok := parseDestination(" 10.0.0.1:5432 ")
	require.True(t, ok)
	assert.Equal(t, "10.0.0.1", d.IP)
	assert.Equal(t, int32(5432), d.Port)
	assert.Equal(t, corev1.ProtocolTCP, d.Protocol)

	d, ok = parseDestination("[2001:db8::1]:443")
	require.True(t, ok)
	assert.Equal(t, "2001:db8::1", d.IP)

	for _, bad := range []string{"", "10.0.0.1", "10.0.0.1:0", "10.0.0.1:http", "postgres:5432", "10.0.0.1:99999"} {
		_, ok := parseDestination(bad)
		assert.False(t, ok, "a malformed entry that became a rule would be a rule nobody can trace: %q", bad)
	}
}

func TestWorkloadOfPrefersTheOwner(t *testing.T) {
	ns, w := workloadOf(netpolProfile("prod", "p", "web-1", "Deployment", "web"))
	assert.Equal(t, "prod", ns)
	assert.Equal(t, "Deployment/web", w)

	bare := &policyv1alpha1.ContainerProfile{
		ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "p"},
		Spec:       policyv1alpha1.ContainerProfileSpec{PodName: "loose"},
	}
	ns, w = workloadOf(bare)
	assert.Equal(t, "prod", ns)
	assert.Equal(t, "Pod/loose", w)

	_, w = workloadOf(&policyv1alpha1.ContainerProfile{})
	assert.Empty(t, w, "a profile that names neither a workload nor a pod is not evidence about anything")
}

func TestBuildRosterResolvesTheWorkloadExactly(t *testing.T) {
	// The usual shortcut is to strip the hash off a ReplicaSet's name, which
	// is wrong for a Deployment whose own name ends in something hash-shaped.
	// One list per kind resolves it instead.
	fc, _ := installFakeClients(t,
		netpolPod("prod", "web-abc-1", "10.0.0.1", "web-abc", map[string]string{"app": "web"}),
		netpolReplicaSet("prod", "web-abc", "web-7f4d"),
		netpolPod("prod", "solo", "10.0.0.9", "", nil),
	)

	roster, err := buildRoster(context.Background(), fc, nil)
	require.NoError(t, err)
	require.Len(t, roster, 2)

	byName := map[string]netpol.Pod{}
	for _, p := range roster {
		byName[p.Name] = p
	}
	assert.Equal(t, "Deployment/web-7f4d", byName["web-abc-1"].Workload)
	assert.Empty(t, byName["solo"].Workload, "a pod with no controller is not part of a workload")
}

func TestBuildRosterMapsAJobToItsCronJob(t *testing.T) {
	// Grouping by the Job would make every nightly run its own workload and
	// every generated policy a single-use one.
	yes := true
	job := &batchv1.Job{ObjectMeta: metav1.ObjectMeta{
		Namespace: "prod", Name: "backup-28000",
		OwnerReferences: []metav1.OwnerReference{{
			APIVersion: "batch/v1", Kind: "CronJob", Name: "backup", Controller: &yes,
		}},
	}}
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: "prod", Name: "backup-28000-xyz",
			OwnerReferences: []metav1.OwnerReference{{
				APIVersion: "batch/v1", Kind: "Job", Name: "backup-28000", Controller: &yes,
			}},
		},
	}
	fc, _ := installFakeClients(t, job, pod)

	roster, err := buildRoster(context.Background(), fc, nil)
	require.NoError(t, err)
	require.Len(t, roster, 1)
	assert.Equal(t, "CronJob/backup", roster[0].Workload)
}

func TestFoldProfilesJoinsTheContainersOfOneWorkload(t *testing.T) {
	// Containers of a pod share its network namespace, so their learned
	// destinations are one workload's traffic and not several.
	fc, _ := installFakeClients(t,
		netpolProfile("prod", "a", "web-1", "Deployment", "web", "10.0.1.1:8080"),
		netpolProfile("prod", "b", "web-1", "Deployment", "web", "10.0.1.1:8080", "10.0.1.1:53"),
		netpolProfile("prod", "c", "web-2", "Deployment", "web", "10.0.2.2:443"),
	)
	var list policyv1alpha1.ContainerProfileList
	require.NoError(t, fc.List(context.Background(), &list))

	obs := foldProfiles(context.Background(), fc, list.Items)
	require.Len(t, obs, 1)
	assert.Equal(t, "Deployment/web", obs[0].Workload)
	assert.Equal(t, []string{"web-1", "web-2"}, obs[0].Pods)
	assert.Len(t, obs[0].Destinations, 3, "the same destination seen twice is one destination")
	assert.Equal(t, "10.0.1.1", obs[0].Destinations[0].IP, "destinations are sorted so a rerun is not a diff")
}

func TestFoldProfilesSkipsAProfileThatNamesNothing(t *testing.T) {
	obs := foldProfiles(context.Background(), nil, []policyv1alpha1.ContainerProfile{{}})
	assert.Empty(t, obs)
}

func TestWindowLookupReadsThePolicyAndTheSchedule(t *testing.T) {
	yes := true
	pol := &policyv1alpha1.PahlevanPolicy{
		ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "nightly"},
		Spec: policyv1alpha1.PahlevanPolicySpec{
			LearningConfig: policyv1alpha1.LearningConfig{
				Duration: &metav1.Duration{Duration: 50 * time.Minute},
			},
		},
	}
	cron := &batchv1.CronJob{
		ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "backup"},
		Spec:       batchv1.CronJobSpec{Schedule: "0 3 * * *"},
	}
	job := &batchv1.Job{ObjectMeta: metav1.ObjectMeta{
		Namespace: "prod", Name: "backup-1",
		OwnerReferences: []metav1.OwnerReference{{
			APIVersion: "batch/v1", Kind: "CronJob", Name: "backup", Controller: &yes,
		}},
	}}
	pod := &corev1.Pod{ObjectMeta: metav1.ObjectMeta{
		Namespace: "prod", Name: "backup-1-xyz",
		OwnerReferences: []metav1.OwnerReference{{
			APIVersion: "batch/v1", Kind: "Job", Name: "backup-1", Controller: &yes,
		}},
	}}
	fc, _ := installFakeClients(t, pol, cron, job, pod)

	profile := netpolProfile("prod", "p", "backup-1-xyz", "CronJob", "backup")
	profile.Spec.PolicyRef = "nightly"

	w := newWindowLookup(fc)
	window, schedule := w.for_(context.Background(), profile)
	assert.Equal(t, 50*time.Minute, window)
	assert.Equal(t, "0 3 * * *", schedule, "the schedule is two hops above the pod and is never on it")

	// Cached: a second ask must not re-read the policy.
	require.NoError(t, fc.Delete(context.Background(), pol))
	again, _ := w.for_(context.Background(), profile)
	assert.Equal(t, 50*time.Minute, again)
}

func TestWindowLookupSurvivesAMissingPodAndPolicy(t *testing.T) {
	fc, _ := installFakeClients(t)
	w := newWindowLookup(fc)

	profile := netpolProfile("prod", "p", "gone", "Deployment", "web")
	profile.Spec.PolicyRef = "absent"
	window, schedule := w.for_(context.Background(), profile)
	assert.Zero(t, window)
	assert.Empty(t, schedule)

	noPod := netpolProfile("prod", "p", "", "Deployment", "web")
	window, schedule = w.for_(context.Background(), noPod)
	assert.Zero(t, window)
	assert.Empty(t, schedule)
}

func TestWindowLookupSurfacesACycleTheWindowCannotCover(t *testing.T) {
	// The end-to-end version of the learning-window caveat: a monthly CronJob
	// and an hour of learning. pkg/cycle caps at a week, so the report has to
	// say the baseline cannot contain a period.
	yes := true
	installFakeClients(t,
		&policyv1alpha1.PahlevanPolicy{
			ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "monthly"},
			Spec: policyv1alpha1.PahlevanPolicySpec{
				LearningConfig: policyv1alpha1.LearningConfig{Duration: &metav1.Duration{Duration: time.Hour}},
			},
		},
		&batchv1.CronJob{
			ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "close"},
			Spec:       batchv1.CronJobSpec{Schedule: "0 0 1 * *"},
		},
		&batchv1.Job{ObjectMeta: metav1.ObjectMeta{
			Namespace: "prod", Name: "close-1",
			OwnerReferences: []metav1.OwnerReference{{
				APIVersion: "batch/v1", Kind: "CronJob", Name: "close", Controller: &yes,
			}},
		}},
		&corev1.Pod{
			ObjectMeta: metav1.ObjectMeta{
				Namespace: "prod", Name: "close-1-xyz", Labels: map[string]string{"app": "close"},
				OwnerReferences: []metav1.OwnerReference{{
					APIVersion: "batch/v1", Kind: "Job", Name: "close-1", Controller: &yes,
				}},
			},
			Status: corev1.PodStatus{PodIP: "10.0.4.1"},
		},
		func() crclient.Object {
			p := netpolProfile("prod", "close-main", "close-1-xyz", "CronJob", "close", "10.0.9.9:5432")
			p.Spec.PolicyRef = "monthly"
			return p
		}(),
	)

	out, err := runNetpol(t, "-n", "prod")
	require.NoError(t, err)
	assert.Contains(t, out, "cannot contain a whole period")
}

func TestRenderForDiffStripsServerOwnedFields(t *testing.T) {
	got, err := renderForDiff(&networkingv1.NetworkPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: "prod", Name: "p",
			ResourceVersion:   "123",
			UID:               types.UID("abc"),
			Generation:        7,
			CreationTimestamp: metav1.Now(),
			ManagedFields:     []metav1.ManagedFieldsEntry{{Manager: "kubectl"}},
		},
	})
	require.NoError(t, err)
	for _, noise := range []string{"123", "abc", "generation", "creationTimestamp: \"2", "managedFields"} {
		assert.NotContains(t, got, noise)
	}
	assert.Contains(t, got, "apiVersion: networking.k8s.io/v1")
}

func TestParseDirection(t *testing.T) {
	for _, tc := range []struct {
		in              string
		egress, ingress bool
	}{
		{"both", true, true}, {"", true, true}, {"EGRESS", true, false}, {"ingress", false, true},
	} {
		e, i, err := parseDirection(tc.in)
		require.NoError(t, err)
		assert.Equal(t, tc.egress, e)
		assert.Equal(t, tc.ingress, i)
	}
}

func TestNetpolJSONShape(t *testing.T) {
	out := netpolJSON(netpol.Result{Subjects: []netpol.Subject{{
		Namespace: "prod", Workload: "Deployment/web", Observed: 2,
		Findings: []netpol.Finding{{Level: netpol.LevelWarn, Message: "something"}},
	}}})
	require.Len(t, out.Subjects, 1)
	assert.Empty(t, out.Subjects[0].Selector, "an unusable selector must not be printed as though it were real")
	assert.Equal(t, []string{"warn: something"}, out.Subjects[0].Findings)

	withWindow := netpolJSON(netpol.Result{Subjects: []netpol.Subject{{
		Namespace: "prod", Workload: "Deployment/web",
		Window: cycle.Requirement{Window: time.Hour, Cycle: 30 * 24 * time.Hour, Source: cycle.SourceCap},
	}}})
	assert.Equal(t, "1h0m0s", withWindow.Subjects[0].Window)
	assert.True(t, withWindow.Subjects[0].Capped)
}

func TestWorkloadOfPodUsesADirectController(t *testing.T) {
	// A StatefulSet owns its pods directly, with no ReplicaSet in between.
	yes := true
	p := &corev1.Pod{ObjectMeta: metav1.ObjectMeta{
		Namespace: "prod", Name: "pg-0",
		OwnerReferences: []metav1.OwnerReference{{
			APIVersion: "apps/v1", Kind: "StatefulSet", Name: "pg", Controller: &yes,
		}},
	}}
	assert.Equal(t, "StatefulSet/pg", workloadOfPod(p, map[string]string{}))
}

func TestWindowLookupFallsBackToTheObjectNamespace(t *testing.T) {
	// A profile written without spec.namespace is still in a namespace: its
	// own. Reading the policy from "" would look in the wrong place.
	pol := &policyv1alpha1.PahlevanPolicy{
		ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "p"},
		Spec: policyv1alpha1.PahlevanPolicySpec{
			LearningConfig: policyv1alpha1.LearningConfig{
				Duration: &metav1.Duration{Duration: 20 * time.Minute},
			},
		},
	}
	fc, _ := installFakeClients(t, pol,
		&corev1.Pod{ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "solo"}})

	profile := &policyv1alpha1.ContainerProfile{
		ObjectMeta: metav1.ObjectMeta{Namespace: "prod", Name: "cp"},
		Spec:       policyv1alpha1.ContainerProfileSpec{PodName: "solo", PolicyRef: "p"},
	}
	window, schedule := newWindowLookup(fc).for_(context.Background(), profile)
	assert.Equal(t, 20*time.Minute, window)
	assert.Empty(t, schedule, "a pod with no owner chain has no schedule, and that is not an error")
}

func TestNetpolCommandReportsAnUnreadableCluster(t *testing.T) {
	// A List that fails has to fail the command. Carrying on would generate
	// policies from a partial view of the cluster, which is the one input this
	// tool must never guess at.
	prevK8s, prevReady := k8sClient, clientsReady
	k8sClient = fake.NewClientBuilder().
		WithScheme(cli.GetScheme()).
		WithInterceptorFuncs(interceptor.Funcs{
			List: func(ctx context.Context, c crclient.WithWatch, list crclient.ObjectList,
				opts ...crclient.ListOption,
			) error {
				return errors.New("the API server said no")
			},
		}).Build()
	clientsReady = true
	t.Cleanup(func() { k8sClient, clientsReady = prevK8s, prevReady })

	_, err := runNetpol(t, "-n", "prod")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing container profiles")
}

// brokenWriter fails every write, which is what a closed pipe looks like to a
// command whose output is being piped into something that exited.
type brokenWriter struct{}

func (brokenWriter) Write([]byte) (int, error) { return 0, errors.New("broken pipe") }

func TestNetpolReportsAWriteFailureRatherThanExitingZero(t *testing.T) {
	// `pahlevan netpol -o yaml | head -1` closes the pipe. Swallowing that
	// would report success for output nobody received.
	fc, _ := installFakeClients(t, netpolCluster()...)
	obs, roster, err := collectBaseline(context.Background(), fc, "prod", false)
	require.NoError(t, err)
	res := netpol.Generate(obs, netpol.Options{
		Roster: roster, Resolver: netpol.NewRosterResolver(roster), Egress: true,
	})

	for _, format := range []string{"yaml", "report"} {
		err := writeNetpol(context.Background(), brokenWriter{}, fc, res, format, false, len(obs))
		assert.Error(t, err, "format %q", format)
	}
}

func TestNetpolCommandFailsWhenThePodListingIsRefused(t *testing.T) {
	// The profiles are readable and the pods are not. Generating from that is
	// generating a selector against a namespace this command cannot see.
	prevK8s, prevReady := k8sClient, clientsReady
	base := fake.NewClientBuilder().WithScheme(cli.GetScheme()).WithObjects(netpolCluster()...).Build()
	k8sClient = fake.NewClientBuilder().
		WithScheme(cli.GetScheme()).
		WithObjects(netpolCluster()...).
		WithInterceptorFuncs(interceptor.Funcs{
			List: func(ctx context.Context, c crclient.WithWatch, list crclient.ObjectList,
				opts ...crclient.ListOption,
			) error {
				if _, ok := list.(*corev1.PodList); ok {
					return errors.New("forbidden")
				}
				return base.List(ctx, list, opts...)
			},
		}).Build()
	clientsReady = true
	t.Cleanup(func() { k8sClient, clientsReady = prevK8s, prevReady })

	_, err := runNetpol(t, "-n", "prod")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing pods")
}

func TestBuildRosterFailsWhenPodsCannotBeListed(t *testing.T) {
	// Without the pod listing there is nothing to check a selector against,
	// and an unchecked selector is the failure this whole command avoids.
	c := fake.NewClientBuilder().
		WithScheme(cli.GetScheme()).
		WithInterceptorFuncs(interceptor.Funcs{
			List: func(ctx context.Context, cl crclient.WithWatch, list crclient.ObjectList,
				opts ...crclient.ListOption,
			) error {
				if _, ok := list.(*corev1.PodList); ok {
					return errors.New("forbidden")
				}
				return cl.List(ctx, list, opts...)
			},
		}).Build()

	_, err := buildRoster(context.Background(), c, nil)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "listing pods")
}
