apiVersion: v1
entries:
  pahlevan-operator:
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.3.2
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.3.2
    created: "2026-09-07T23:54:30.055119026+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 70f449a512d92886fd4b4084db938d838e2904088309b23944ce58be31f6c754
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.3.2.tgz
    version: 3.3.2
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.3.1
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.3.1
    created: "2026-09-07T23:54:30.054497205+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 9736b6eebc9768ed3a3d01a7b69080c365e58016594d5d68c03397ae5c74bba1
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.3.1.tgz
    version: 3.3.1
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.3.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.3.0
    created: "2026-09-07T23:54:30.053916395+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 74017d70355326c84b845a751c759339aa89b1d18de416b3b6ba9757a42ed279
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.3.0.tgz
    version: 3.3.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.2.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.2.0
    created: "2026-09-07T23:54:30.053220343+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 39db94f8a01788d6c6ce0ee1aa1bb49e4a2b7f000f61568e87379e14d4eb0ff9
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.2.0.tgz
    version: 3.2.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.1.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.1.0
    created: "2026-09-07T23:54:30.052634303+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 1b58f9238c16ba893dfd6e16a506a5565f3584a75521ae95d2b1476d987e58c5
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.1.0.tgz
    version: 3.1.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.0.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.0.0
    created: "2026-09-07T23:54:30.052035972+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: a2ca3e4bfd6eaf82648e2fa2b6163c693b821d09312b74f8db7cfce4ccdc7875
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.0.0.tgz
    version: 3.0.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v2.0.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v2.0.0
    created: "2026-09-07T23:54:30.051391511+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 0f5f8ace8b4e1b06c7c149542b042affedafecd68e80f3c9c0c1498a0af06c03
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-2.0.0.tgz
    version: 2.0.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan-operator
          image: ghcr.io/obsernetics/pahlevan:v1.0.0
        - name: pahlevan-operator-debug
          image: ghcr.io/obsernetics/pahlevan:debug-v1.0.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v1.0.0
    created: "2026-09-07T23:54:30.05076108+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 80dfdcc1513c010690da6a5c80b8630a121a075dcc49960d2326b708c08746bf
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-1.0.0.tgz
    version: 1.0.0
generated: "2026-09-07T23:54:30.050047317+02:00"
