apiVersion: v1
entries:
  pahlevan-operator:
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v3.0.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v3.0.0
    created: "2026-08-31T15:33:51.180350237+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: a2ca3e4bfd6eaf82648e2fa2b6163c693b821d09312b74f8db7cfce4ccdc7875
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-3.0.0.tgz
    version: 3.0.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan
          image: ghcr.io/obsernetics/pahlevan:v2.0.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v2.0.0
    created: "2026-08-31T15:33:51.178955769+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 0f5f8ace8b4e1b06c7c149542b042affedafecd68e80f3c9c0c1498a0af06c03
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-2.0.0.tgz
    version: 2.0.0
  - annotations:
      category: Security
      images: |
        - name: pahlevan-operator
          image: ghcr.io/obsernetics/pahlevan:v1.0.0
        - name: pahlevan-operator-debug
          image: ghcr.io/obsernetics/pahlevan:debug-v1.0.0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: v1.0.0
    created: "2026-08-31T15:33:51.178283471+02:00"
    description: A Helm chart for Pahlevan eBPF-based Kubernetes Security Operator
    digest: 80dfdcc1513c010690da6a5c80b8630a121a075dcc49960d2326b708c08746bf
    home: https://github.com/obsernetics/pahlevan
    keywords:
    - security
    - ebpf
    - kubernetes
    - operator
    - monitoring
    - attack-surface
    - syscall-monitoring
    kubeVersion: '>=1.24.0'
    maintainers:
    - email: team@obsernetics.com
      name: Obsernetics Team
    name: pahlevan-operator
    sources:
    - https://github.com/obsernetics/pahlevan
    type: application
    urls:
    - https://obsernetics.github.io/pahlevan/charts/pahlevan-operator-1.0.0.tgz
    version: 1.0.0
generated: "2026-08-31T15:33:51.177499071+02:00"
