apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ../../config/crd/pahlevanpolicy_crd.yaml
- serviceaccount.yaml
- rbac.yaml
- daemonset-agent.yaml
- deployment-operator.yaml
- service.yaml

images:
- name: ghcr.io/obsernetics/pahlevan
  newTag: latest
