apiVersion: v1
kind: ServiceAccount
metadata:
  name: pahlevan-agent
  namespace: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan-agent
    app.kubernetes.io/part-of: pahlevan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pahlevan-operator
  namespace: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan-operator
    app.kubernetes.io/part-of: pahlevan
