apiVersion: v1
kind: Service
metadata:
  name: pahlevan-agent-metrics
  namespace: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan-agent
    app.kubernetes.io/part-of: pahlevan
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pahlevan-agent
---
apiVersion: v1
kind: Service
metadata:
  name: pahlevan-operator-metrics
  namespace: pahlevan-system
  labels:
    app.kubernetes.io/name: pahlevan-operator
    app.kubernetes.io/part-of: pahlevan
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app.kubernetes.io/name: pahlevan-operator
