#!/usr/bin/env bash
# Generate the all-in-one install.yaml from deploy/base + the CRD.
# Usage: scripts/gen-install.sh > install.yaml
set -euo pipefail
cd "$(dirname "$0")/.."

emit() {
  # Print a document separator then the file, guaranteeing surrounding newlines
  # (some source files lack a trailing newline).
  printf -- '---\n'
  cat "$1"
  printf '\n'
}

{
  printf '# Pahlevan - all-in-one install manifest.\n'
  printf '# Generated by scripts/gen-install.sh from deploy/base + config/crd.\n'
  printf '# Deploys: namespace, CRD, RBAC, agent DaemonSet, operator Deployment.\n'
  emit deploy/base/namespace.yaml
  emit config/crd/policy.pahlevan.io_pahlevanpolicies.yaml
  emit config/crd/policy.pahlevan.io_containerprofiles.yaml
  emit config/crd/policy.pahlevan.io_attacksurfaces.yaml
  emit deploy/base/serviceaccount.yaml
  emit deploy/base/rbac.yaml
  emit deploy/base/daemonset-agent.yaml
  emit deploy/base/deployment-operator.yaml
  emit deploy/base/service.yaml
}
