#!/usr/bin/env bash
# Generate the all-in-one install.yaml from deploy/base + the CRD.
# Usage: scripts/gen-install.sh > install.yaml
set -euo pipefail
cd "$(dirname "$0")/.."

# The image tag is pinned to the release, not left at :latest.
#
# deploy/base carries :latest because it is a kustomize base and an overlay is
# expected to set its own tag. install.yaml is not that. It is attached to a
# GitHub release, and docs/packages.md points at
# releases/download/<version>/install.yaml as the immutable, recommended
# production path. Shipping :latest inside it meant that path pinned nothing:
# every node pulled a tag that moves on each merge to main, which is the exact
# opposite of what the reader was promised.
VERSION="$(sed -n 's/^VERSION?=\(v[0-9][^ \t]*\).*/\1/p' Makefile | head -1)"
if [ -z "${VERSION}" ]; then
  echo "gen-install.sh: no VERSION?= line in the Makefile to pin the image to" >&2
  exit 1
fi

emit() {
  # Print a document separator then the file, guaranteeing surrounding newlines
  # (some source files lack a trailing newline), with the image tag pinned.
  printf -- '---\n'
  sed "s|\(image: ghcr\.io/obsernetics/pahlevan\):latest|\1:${VERSION}|" "$1"
  printf '\n'
}

{
  printf '# Pahlevan - all-in-one install manifest.\n'
  printf '# Generated by scripts/gen-install.sh from deploy/base + config/crd.\n'
  printf '# Deploys: namespace, CRD, RBAC, agent DaemonSet, operator Deployment.\n'
  printf '# Image pinned to %s.\n' "${VERSION}"
  emit deploy/base/namespace.yaml
  emit config/crd/policy.pahlevan.io_pahlevanpolicies.yaml
  emit config/crd/policy.pahlevan.io_containerprofiles.yaml
  emit config/crd/policy.pahlevan.io_attacksurfaces.yaml
  emit deploy/base/serviceaccount.yaml
  emit deploy/base/rbac.yaml
  emit deploy/base/daemonset-agent.yaml
  emit deploy/base/deployment-operator.yaml
  emit deploy/base/service.yaml
}
