// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadCapabilityMonitor returns the embedded CollectionSpec for CapabilityMonitor.
func LoadCapabilityMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CapabilityMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CapabilityMonitor: %w", err)
	}

	return spec, err
}

// LoadCapabilityMonitorObjects loads CapabilityMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CapabilityMonitorObjects
//	*CapabilityMonitorPrograms
//	*CapabilityMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCapabilityMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCapabilityMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CapabilityMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapabilityMonitorSpecs struct {
	CapabilityMonitorProgramSpecs
	CapabilityMonitorMapSpecs
	CapabilityMonitorVariableSpecs
}

// CapabilityMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapabilityMonitorProgramSpecs struct {
	CapableCheck *ebpf.ProgramSpec `ebpf:"capable_check"`
}

// CapabilityMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapabilityMonitorMapSpecs struct {
	CapAllowed *ebpf.MapSpec `ebpf:"cap_allowed"`
	CapEvents  *ebpf.MapSpec `ebpf:"cap_events"`
	CapMode    *ebpf.MapSpec `ebpf:"cap_mode"`
}

// CapabilityMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CapabilityMonitorVariableSpecs struct {
}

// CapabilityMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCapabilityMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapabilityMonitorObjects struct {
	CapabilityMonitorPrograms
	CapabilityMonitorMaps
	CapabilityMonitorVariables
}

func (o *CapabilityMonitorObjects) Close() error {
	return _CapabilityMonitorClose(
		&o.CapabilityMonitorPrograms,
		&o.CapabilityMonitorMaps,
	)
}

// CapabilityMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCapabilityMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapabilityMonitorMaps struct {
	CapAllowed *ebpf.Map `ebpf:"cap_allowed"`
	CapEvents  *ebpf.Map `ebpf:"cap_events"`
	CapMode    *ebpf.Map `ebpf:"cap_mode"`
}

func (m *CapabilityMonitorMaps) Close() error {
	return _CapabilityMonitorClose(
		m.CapAllowed,
		m.CapEvents,
		m.CapMode,
	)
}

// CapabilityMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCapabilityMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapabilityMonitorVariables struct {
}

// CapabilityMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCapabilityMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CapabilityMonitorPrograms struct {
	CapableCheck *ebpf.Program `ebpf:"capable_check"`
}

func (p *CapabilityMonitorPrograms) Close() error {
	return _CapabilityMonitorClose(
		p.CapableCheck,
	)
}

func _CapabilityMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed capabilitymonitor_bpfeb.o
var _CapabilityMonitorBytes []byte
