// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadCredMonitor returns the embedded CollectionSpec for CredMonitor.
func LoadCredMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CredMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CredMonitor: %w", err)
	}

	return spec, err
}

// LoadCredMonitorObjects loads CredMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CredMonitorObjects
//	*CredMonitorPrograms
//	*CredMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCredMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCredMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CredMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredMonitorSpecs struct {
	CredMonitorProgramSpecs
	CredMonitorMapSpecs
	CredMonitorVariableSpecs
}

// CredMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredMonitorProgramSpecs struct {
	HandleCommitCreds *ebpf.ProgramSpec `ebpf:"handle_commit_creds"`
}

// CredMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredMonitorMapSpecs struct {
	CredConfig   *ebpf.MapSpec `ebpf:"cred_config"`
	CredEvents   *ebpf.MapSpec `ebpf:"cred_events"`
	CredGoverned *ebpf.MapSpec `ebpf:"cred_governed"`
}

// CredMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CredMonitorVariableSpecs struct {
}

// CredMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCredMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredMonitorObjects struct {
	CredMonitorPrograms
	CredMonitorMaps
	CredMonitorVariables
}

func (o *CredMonitorObjects) Close() error {
	return _CredMonitorClose(
		&o.CredMonitorPrograms,
		&o.CredMonitorMaps,
	)
}

// CredMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCredMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredMonitorMaps struct {
	CredConfig   *ebpf.Map `ebpf:"cred_config"`
	CredEvents   *ebpf.Map `ebpf:"cred_events"`
	CredGoverned *ebpf.Map `ebpf:"cred_governed"`
}

func (m *CredMonitorMaps) Close() error {
	return _CredMonitorClose(
		m.CredConfig,
		m.CredEvents,
		m.CredGoverned,
	)
}

// CredMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCredMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredMonitorVariables struct {
}

// CredMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCredMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type CredMonitorPrograms struct {
	HandleCommitCreds *ebpf.Program `ebpf:"handle_commit_creds"`
}

func (p *CredMonitorPrograms) Close() error {
	return _CredMonitorClose(
		p.HandleCommitCreds,
	)
}

func _CredMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed credmonitor_x86_bpfel.o
var _CredMonitorBytes []byte
