// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadExecMonitor returns the embedded CollectionSpec for ExecMonitor.
func LoadExecMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ExecMonitor: %w", err)
	}

	return spec, err
}

// LoadExecMonitorObjects loads ExecMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecMonitorObjects
//	*ExecMonitorPrograms
//	*ExecMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorSpecs struct {
	ExecMonitorProgramSpecs
	ExecMonitorMapSpecs
	ExecMonitorVariableSpecs
}

// ExecMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorProgramSpecs struct {
	BprmCheck *ebpf.ProgramSpec `ebpf:"bprm_check"`
}

// ExecMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorMapSpecs struct {
	ExecAllowed *ebpf.MapSpec `ebpf:"exec_allowed"`
	ExecEvents  *ebpf.MapSpec `ebpf:"exec_events"`
	ExecMode    *ebpf.MapSpec `ebpf:"exec_mode"`
}

// ExecMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorVariableSpecs struct {
}

// ExecMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorObjects struct {
	ExecMonitorPrograms
	ExecMonitorMaps
	ExecMonitorVariables
}

func (o *ExecMonitorObjects) Close() error {
	return _ExecMonitorClose(
		&o.ExecMonitorPrograms,
		&o.ExecMonitorMaps,
	)
}

// ExecMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorMaps struct {
	ExecAllowed *ebpf.Map `ebpf:"exec_allowed"`
	ExecEvents  *ebpf.Map `ebpf:"exec_events"`
	ExecMode    *ebpf.Map `ebpf:"exec_mode"`
}

func (m *ExecMonitorMaps) Close() error {
	return _ExecMonitorClose(
		m.ExecAllowed,
		m.ExecEvents,
		m.ExecMode,
	)
}

// ExecMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorVariables struct {
}

// ExecMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorPrograms struct {
	BprmCheck *ebpf.Program `ebpf:"bprm_check"`
}

func (p *ExecMonitorPrograms) Close() error {
	return _ExecMonitorClose(
		p.BprmCheck,
	)
}

func _ExecMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execmonitor_bpfeb.o
var _ExecMonitorBytes []byte
