// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ExecMonitorExecArgs struct {
	_         structs.HostLayout
	Argc      uint32
	Len       uint32
	Truncated uint8
	Buf       [256]uint8
	_         [3]byte
}

// LoadExecMonitor returns the embedded CollectionSpec for ExecMonitor.
func LoadExecMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ExecMonitor: %w", err)
	}

	return spec, err
}

// LoadExecMonitorObjects loads ExecMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ExecMonitorObjects
//	*ExecMonitorPrograms
//	*ExecMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadExecMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadExecMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ExecMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorSpecs struct {
	ExecMonitorProgramSpecs
	ExecMonitorMapSpecs
	ExecMonitorVariableSpecs
}

// ExecMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorProgramSpecs struct {
	BprmCheck          *ebpf.ProgramSpec `ebpf:"bprm_check"`
	HandleExecveArgs   *ebpf.ProgramSpec `ebpf:"handle_execve_args"`
	HandleExecveatArgs *ebpf.ProgramSpec `ebpf:"handle_execveat_args"`
	HandleSchedExit    *ebpf.ProgramSpec `ebpf:"handle_sched_exit"`
}

// ExecMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorMapSpecs struct {
	ExecAllowed     *ebpf.MapSpec `ebpf:"exec_allowed"`
	ExecArgsBuild   *ebpf.MapSpec `ebpf:"exec_args_build"`
	ExecArgsScratch *ebpf.MapSpec `ebpf:"exec_args_scratch"`
	ExecEvents      *ebpf.MapSpec `ebpf:"exec_events"`
	ExecMode        *ebpf.MapSpec `ebpf:"exec_mode"`
}

// ExecMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ExecMonitorVariableSpecs struct {
}

// ExecMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorObjects struct {
	ExecMonitorPrograms
	ExecMonitorMaps
	ExecMonitorVariables
}

func (o *ExecMonitorObjects) Close() error {
	return _ExecMonitorClose(
		&o.ExecMonitorPrograms,
		&o.ExecMonitorMaps,
	)
}

// ExecMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorMaps struct {
	ExecAllowed     *ebpf.Map `ebpf:"exec_allowed"`
	ExecArgsBuild   *ebpf.Map `ebpf:"exec_args_build"`
	ExecArgsScratch *ebpf.Map `ebpf:"exec_args_scratch"`
	ExecEvents      *ebpf.Map `ebpf:"exec_events"`
	ExecMode        *ebpf.Map `ebpf:"exec_mode"`
}

func (m *ExecMonitorMaps) Close() error {
	return _ExecMonitorClose(
		m.ExecAllowed,
		m.ExecArgsBuild,
		m.ExecArgsScratch,
		m.ExecEvents,
		m.ExecMode,
	)
}

// ExecMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorVariables struct {
}

// ExecMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadExecMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ExecMonitorPrograms struct {
	BprmCheck          *ebpf.Program `ebpf:"bprm_check"`
	HandleExecveArgs   *ebpf.Program `ebpf:"handle_execve_args"`
	HandleExecveatArgs *ebpf.Program `ebpf:"handle_execveat_args"`
	HandleSchedExit    *ebpf.Program `ebpf:"handle_sched_exit"`
}

func (p *ExecMonitorPrograms) Close() error {
	return _ExecMonitorClose(
		p.BprmCheck,
		p.HandleExecveArgs,
		p.HandleExecveatArgs,
		p.HandleSchedExit,
	)
}

func _ExecMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execmonitor_x86_bpfel.o
var _ExecMonitorBytes []byte
