// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FileMonitorFconfig struct {
	_        structs.HostLayout
	Disabled uint8
}

// LoadFileMonitor returns the embedded CollectionSpec for FileMonitor.
func LoadFileMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FileMonitor: %w", err)
	}

	return spec, err
}

// LoadFileMonitorObjects loads FileMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileMonitorObjects
//	*FileMonitorPrograms
//	*FileMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFileMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorSpecs struct {
	FileMonitorProgramSpecs
	FileMonitorMapSpecs
	FileMonitorVariableSpecs
}

// FileMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorProgramSpecs struct {
	FileOpen *ebpf.ProgramSpec `ebpf:"file_open"`
}

// FileMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorMapSpecs struct {
	FileConfig *ebpf.MapSpec `ebpf:"file_config"`
	FileEvents *ebpf.MapSpec `ebpf:"file_events"`
	FileSeen   *ebpf.MapSpec `ebpf:"file_seen"`
}

// FileMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileMonitorVariableSpecs struct {
}

// FileMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorObjects struct {
	FileMonitorPrograms
	FileMonitorMaps
	FileMonitorVariables
}

func (o *FileMonitorObjects) Close() error {
	return _FileMonitorClose(
		&o.FileMonitorPrograms,
		&o.FileMonitorMaps,
	)
}

// FileMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorMaps struct {
	FileConfig *ebpf.Map `ebpf:"file_config"`
	FileEvents *ebpf.Map `ebpf:"file_events"`
	FileSeen   *ebpf.Map `ebpf:"file_seen"`
}

func (m *FileMonitorMaps) Close() error {
	return _FileMonitorClose(
		m.FileConfig,
		m.FileEvents,
		m.FileSeen,
	)
}

// FileMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorVariables struct {
}

// FileMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileMonitorPrograms struct {
	FileOpen *ebpf.Program `ebpf:"file_open"`
}

func (p *FileMonitorPrograms) Close() error {
	return _FileMonitorClose(
		p.FileOpen,
	)
}

func _FileMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filemonitor_bpfeb.o
var _FileMonitorBytes []byte
