// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type GenericKprobeKpConfig struct {
	_          structs.HostLayout
	Action     uint32
	Nselectors uint8
	Scoped     uint8
	Pad        uint16
	Sel        [4]struct {
		_     structs.HostLayout
		Src   uint8
		Arg   uint8
		Op    uint8
		Pad   uint8
		Pad2  uint32
		Value uint64
	}
}

type GenericKprobeKpEvent struct {
	_           structs.HostLayout
	CgroupId    uint64
	TimestampNs uint64
	ProbeId     uint64
	Args        [5]uint64
	Pid         uint32
	Tid         uint32
	Uid         uint32
	Gid         uint32
	Flags       uint32
	Pad         uint32
	Comm        [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	GenericKprobeMapKpConfig       = "kp_config"
	GenericKprobeMapKpEvents       = "kp_events"
	GenericKprobeMapKpGoverned     = "kp_governed"
	GenericKprobeMapKpRuntime      = "kp_runtime"
	GenericKprobeMapKpScratch      = "kp_scratch"
	GenericKprobeProgGenericKprobe = "generic_kprobe"
)

// LoadGenericKprobe returns the embedded CollectionSpec for GenericKprobe.
func LoadGenericKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GenericKprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load GenericKprobe: %w", err)
	}

	return spec, err
}

// LoadGenericKprobeObjects loads GenericKprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GenericKprobeObjects
//	*GenericKprobePrograms
//	*GenericKprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGenericKprobeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGenericKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GenericKprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GenericKprobeSpecs struct {
	GenericKprobeProgramSpecs
	GenericKprobeMapSpecs
	GenericKprobeVariableSpecs
}

// GenericKprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GenericKprobeProgramSpecs struct {
	GenericKprobe *ebpf.ProgramSpec `ebpf:"generic_kprobe"`
}

// GenericKprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GenericKprobeMapSpecs struct {
	KpConfig   *ebpf.MapSpec `ebpf:"kp_config"`
	KpEvents   *ebpf.MapSpec `ebpf:"kp_events"`
	KpGoverned *ebpf.MapSpec `ebpf:"kp_governed"`
	KpRuntime  *ebpf.MapSpec `ebpf:"kp_runtime"`
	KpScratch  *ebpf.MapSpec `ebpf:"kp_scratch"`
}

// GenericKprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GenericKprobeVariableSpecs struct {
}

// GenericKprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGenericKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type GenericKprobeObjects struct {
	GenericKprobePrograms
	GenericKprobeMaps
	GenericKprobeVariables
}

func (o *GenericKprobeObjects) Close() error {
	return _GenericKprobeClose(
		&o.GenericKprobePrograms,
		&o.GenericKprobeMaps,
	)
}

// GenericKprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGenericKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type GenericKprobeMaps struct {
	KpConfig   *ebpf.Map `ebpf:"kp_config"`
	KpEvents   *ebpf.Map `ebpf:"kp_events"`
	KpGoverned *ebpf.Map `ebpf:"kp_governed"`
	KpRuntime  *ebpf.Map `ebpf:"kp_runtime"`
	KpScratch  *ebpf.Map `ebpf:"kp_scratch"`
}

func (m *GenericKprobeMaps) Close() error {
	return _GenericKprobeClose(
		m.KpConfig,
		m.KpEvents,
		m.KpGoverned,
		m.KpRuntime,
		m.KpScratch,
	)
}

// GenericKprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGenericKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type GenericKprobeVariables struct {
}

// GenericKprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGenericKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type GenericKprobePrograms struct {
	GenericKprobe *ebpf.Program `ebpf:"generic_kprobe"`
}

func (p *GenericKprobePrograms) Close() error {
	return _GenericKprobeClose(
		p.GenericKprobe,
	)
}

func _GenericKprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed generickprobe_arm64_bpfel.o
var _GenericKprobeBytes []byte
