package ebpf

import (
	"context"
	"encoding/binary"
	"fmt"
	"net"
	"sync"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/prometheus/client_golang/prometheus"
	"go.opentelemetry.io/otel/metric"
	"sigs.k8s.io/controller-runtime/pkg/log"
	ctrlmetrics "sigs.k8s.io/controller-runtime/pkg/metrics"
)

// Package-level counters, registered exactly once (in init) with the
// controller-runtime metrics registry - which is what the agent's metrics server
// actually exposes on :8080/metrics. (The previous code registered per-Manager on
// the DEFAULT registry, which both panicked on a second Manager AND meant the
// pahlevan_* metrics never appeared on the served endpoint.)
//
// These describe the eBPF data plane: what the ring-buffer reader decoded and
// what the kernel denied. They are deliberately named pahlevan_ebpf_* and keyed
// only by event kind. The richer, container-attributed series live in
// pkg/metrics and belong to the policy plane; keeping the two apart avoids two
// packages registering the same metric name with different label dimensions,
// which Prometheus rejects.
const (
	kindSyscall    = "syscall"
	kindNetwork    = "network"
	kindFile       = "file"
	kindExec       = "exec"
	kindCapability = "capability"
)

var eventKinds = []string{kindSyscall, kindNetwork, kindFile, kindExec, kindCapability}

var (
	ebpfEventsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "pahlevan_ebpf_events_total",
		Help: "eBPF events decoded from the ring buffers, by event kind",
	}, []string{"kind"})
	ebpfDenialsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "pahlevan_ebpf_denials_total",
		Help: "Operations denied in-kernel with EPERM, by event kind",
	}, []string{"kind"})
	ebpfDecodeErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "pahlevan_ebpf_decode_errors_total",
		Help: "Ring-buffer records that could not be decoded, by event kind",
	}, []string{"kind"})
)

func init() {
	ctrlmetrics.Registry.MustRegister(
		ebpfEventsTotal, ebpfDenialsTotal, ebpfDecodeErrorsTotal,
	)
	// Pre-create every child so a kind that has not fired yet reports 0 rather
	// than being absent. An absent series and a genuinely idle one look the same
	// on a dashboard, which is exactly the ambiguity an operator cannot afford
	// when the question is "is enforcement working?".
	for _, k := range eventKinds {
		ebpfEventsTotal.WithLabelValues(k)
		ebpfDenialsTotal.WithLabelValues(k)
		ebpfDecodeErrorsTotal.WithLabelValues(k)
	}
}

// dataPlaneCounters holds the per-kind children resolved once, so the hot path
// does not pay for a label lookup on every event.
type dataPlaneCounters struct {
	events, denials, decodeErrors prometheus.Counter
}

func newDataPlaneCounters(kind string) dataPlaneCounters {
	return dataPlaneCounters{
		events:       ebpfEventsTotal.WithLabelValues(kind),
		denials:      ebpfDenialsTotal.WithLabelValues(kind),
		decodeErrors: ebpfDecodeErrorsTotal.WithLabelValues(kind),
	}
}

// All programs are CO-RE (compiled against bpf/vmlinux.h, generated by
// `make vmlinux` from kernel BTF). Regenerate the committed bindings with `make ebpf`.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64,arm64 -cflags "-O2 -g -Wall" SyscallMonitor ../../bpf/syscall_monitor.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64,arm64 -cflags "-O2 -g -Wall" NetworkMonitor ../../bpf/network_monitor.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64,arm64 -cflags "-O2 -g -Wall" FileMonitor ../../bpf/file_monitor.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64,arm64 -cflags "-O2 -g -Wall" ExecMonitor ../../bpf/exec_monitor.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64,arm64 -cflags "-O2 -g -Wall" CapabilityMonitor ../../bpf/capability_monitor.c

type Manager struct {
	mu                 sync.RWMutex
	syscallSpecs       *ebpf.CollectionSpec
	networkSpecs       *ebpf.CollectionSpec
	fileSpecs          *ebpf.CollectionSpec
	syscallCollection  *ebpf.Collection
	networkCollection  *ebpf.Collection
	fileCollection     *ebpf.Collection
	execCollection     *ebpf.Collection
	capCollection      *ebpf.Collection
	syscallLinks       []link.Link
	networkLinks       []link.Link
	fileLinks          []link.Link
	execLinks          []link.Link
	capLinks           []link.Link
	eventReader        *ringbuf.Reader
	networkEventReader *ringbuf.Reader
	fileEventReader    *ringbuf.Reader
	execEventReader    *ringbuf.Reader
	capEventReader     *ringbuf.Reader
	eventHandlers      []EventHandler
	running            bool
	stopCh             chan struct{}
	// counters holds the per-kind data-plane counters, resolved once at
	// construction so the ring-buffer hot path never does a label lookup.
	counters           map[string]dataPlaneCounters
	otelSyscallCounter metric.Int64Counter
	otelNetworkCounter metric.Int64Counter
	otelFileCounter    metric.Int64Counter
	capabilities       *SystemCapabilities
	capabilityChecker  *CapabilityChecker
	mapSizing          MapSizing
}

// The kernel marks a denied operation in the event it emits, so userspace can
// tell an observation apart from an enforcement action without re-deriving the
// decision. These constants are the userspace half of that contract; the
// kernel half lives in bpf/*.c and the two must move together.
const (
	// DeniedFlag is set on FileEvent.Flags, ProcessEvent.Flags and
	// CapabilityEvent.Flags when the operation was denied with EPERM.
	DeniedFlag uint32 = 0x80000000
	// KilledFlag is set on ProcessEvent.Flags when the process was also killed
	// (enforcement mode 2, bpf_send_signal(SIGKILL)).
	KilledFlag uint32 = 0x40000000
	// DeniedDirection is set on NetworkEvent.Direction when the connect was
	// denied. Network events carry no Flags field, so the bit rides here.
	DeniedDirection uint8 = 0x80
)

type EventHandler interface {
	HandleSyscallEvent(event *SyscallEvent) error
	HandleNetworkEvent(event *NetworkEvent) error
	HandleFileEvent(event *FileEvent) error
	HandleProcessEvent(event *ProcessEvent) error
	HandleCapabilityEvent(event *CapabilityEvent) error
}

// ProcessEvent is an execve observed by the LSM bprm_check_security hook.
type ProcessEvent struct {
	PID         uint32
	PPID        uint32 // parent tgid (process ancestry)
	UID         uint32
	Flags       uint32 // 0x80000000 => denied in-kernel, 0x40000000 => killed
	Timestamp   uint64
	CgroupID    uint64
	Comm        string
	ParentComm  string
	Filename    string
	ContainerID string
}

// CapabilityEvent is a capability check observed by the LSM capable hook.
type CapabilityEvent struct {
	PID         uint32
	Capability  uint32 // capability number, e.g. 21 = CAP_SYS_ADMIN
	Flags       uint32 // bit 0x80000000 => denied in-kernel
	Timestamp   uint64
	CgroupID    uint64
	Comm        string
	ContainerID string
}

type SyscallEvent struct {
	PID         uint32
	TGID        uint32
	UID         uint32
	GID         uint32
	SyscallNr   uint64
	Timestamp   uint64
	Comm        string
	CgroupID    uint64 // real attribution key from bpf_get_current_cgroup_id()
	ContainerID string
	Phase       uint8
	Action      uint8
}

type NetworkEvent struct {
	PID         uint32
	TGID        uint32
	SrcIP       uint32
	DstIP       uint32
	SrcPort     uint16
	DstPort     uint16
	Protocol    uint8
	Direction   uint8 // 0 = egress; bit 0x80 = denied in-kernel
	Action      uint8
	Family      uint8    // syscall.AF_INET (2) or AF_INET6 (10)
	DstIP6      [16]byte // IPv6 destination; zero when Family is AF_INET
	Comm        string   // process name, as reported by the kernel
	Timestamp   uint64
	CgroupID    uint64 // real attribution key from bpf_get_current_cgroup_id()
	ContainerID string
}

type FileEvent struct {
	PID         uint32
	TGID        uint32
	UID         uint32
	GID         uint32
	Timestamp   uint64
	SyscallNr   uint32
	Flags       uint32
	Mode        uint16
	Action      uint8
	Comm        string
	CgroupID    uint64 // real attribution key from bpf_get_current_cgroup_id()
	ContainerID string
	Path        string
}

type ContainerPolicy struct {
	AllowedSyscalls  map[uint64]bool
	LastUpdate       time.Time
	LearningWindowMs uint32
	EnforcementMode  uint8
	SelfHealing      bool
}

type NetworkPolicy struct {
	AllowedEgressPorts  map[uint16]bool
	AllowedIngressPorts map[uint16]bool
	AllowedEgressIPs    []uint32
	AllowedIngressIPs   []uint32
	LastUpdate          time.Time
	EnforcementMode     uint8
}

type FilePolicy struct {
	AllowedPaths    []string
	EnforcementMode uint8
	AllowTmpWrites  bool
	AllowProcReads  bool
	AllowDevAccess  bool
	LastUpdate      time.Time
}

func NewManager() (*Manager, error) {
	// Remove memory limit for eBPF
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("failed to remove memory limit: %v", err)
	}

	counters := make(map[string]dataPlaneCounters, len(eventKinds))
	for _, k := range eventKinds {
		counters[k] = newDataPlaneCounters(k)
	}

	// Initialize capability checker and check system capabilities
	capabilityChecker := NewCapabilityChecker()
	capabilities, err := capabilityChecker.CheckSystemCapabilities()
	if err != nil {
		return nil, fmt.Errorf("failed to check system capabilities: %v", err)
	}

	return &Manager{
		stopCh:            make(chan struct{}),
		counters:          counters,
		capabilities:      capabilities,
		capabilityChecker: capabilityChecker,
	}, nil
}

func (m *Manager) LoadPrograms() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Check required capabilities
	if err := m.capabilities.RequireFeature("ebpf"); err != nil {
		return fmt.Errorf("eBPF support check failed: %v", err)
	}

	// The syscall monitor is REQUIRED - it is the core observation program.
	if !m.capabilities.HasTracepointSupport {
		return fmt.Errorf("syscall monitoring requires tracepoint support which is not available on this system. Please ensure debugfs is mounted and kernel has tracepoint support")
	}
	syscallSpecs, err := LoadSyscallMonitor()
	if err != nil {
		return fmt.Errorf("failed to load syscall monitor specs: %v", err)
	}
	applyMapSizing(syscallSpecs, map[string]uint32{
		"syscall_seen": m.mapSizing.SyscallSeen,
		"events":       m.mapSizing.RingBufBytes,
	})
	m.syscallSpecs = syscallSpecs
	syscallColl, err := ebpf.NewCollection(syscallSpecs)
	if err != nil {
		return fmt.Errorf("failed to create syscall collection: %v", err)
	}
	m.syscallCollection = syscallColl

	// The file (LSM) and network monitors are BEST-EFFORT: a kernel without the
	// bpf LSM (file) or without the still-migrating network program should still
	// run the agent in a degraded, syscall-only mode rather than fail outright.
	if fileSpecs, ferr := LoadFileMonitor(); ferr == nil {
		applyMapSizing(fileSpecs, map[string]uint32{
			"file_allowed": m.mapSizing.FileAllowed,
			"file_events":  m.mapSizing.RingBufBytes,
		})
		if fileColl, cerr := ebpf.NewCollection(fileSpecs); cerr == nil {
			m.fileSpecs = fileSpecs
			m.fileCollection = fileColl
		} else {
			log.Log.V(0).Info("file monitor unavailable; continuing without file observation", "error", cerr.Error())
		}
	} else {
		log.Log.V(0).Info("file monitor spec unavailable; continuing without file observation", "error", ferr.Error())
	}

	if netSpecs, nerr := LoadNetworkMonitor(); nerr == nil {
		applyMapSizing(netSpecs, map[string]uint32{
			"network_allowed": m.mapSizing.NetworkAllowed,
			"network_events":  m.mapSizing.RingBufBytes,
		})
		if netColl, cerr := ebpf.NewCollection(netSpecs); cerr == nil {
			m.networkSpecs = netSpecs
			m.networkCollection = netColl
		} else {
			log.Log.V(0).Info("network monitor unavailable; continuing without network observation", "error", cerr.Error())
		}
	} else {
		log.Log.V(0).Info("network monitor spec unavailable; continuing without network observation", "error", nerr.Error())
	}

	if capSpecs, cerr2 := LoadCapabilityMonitor(); cerr2 == nil {
		applyMapSizing(capSpecs, map[string]uint32{"cap_events": m.mapSizing.RingBufBytes})
		if capColl, cerr := ebpf.NewCollection(capSpecs); cerr == nil {
			m.capCollection = capColl
		} else {
			log.Log.V(0).Info("capability monitor unavailable; continuing without capability observation", "error", cerr.Error())
		}
	} else {
		log.Log.V(0).Info("capability monitor spec unavailable", "error", cerr2.Error())
	}

	if execSpecs, eerr := LoadExecMonitor(); eerr == nil {
		applyMapSizing(execSpecs, map[string]uint32{
			"exec_allowed": m.mapSizing.ExecAllowed,
			"exec_events":  m.mapSizing.RingBufBytes,
		})
		if execColl, cerr := ebpf.NewCollection(execSpecs); cerr == nil {
			m.execCollection = execColl
		} else {
			log.Log.V(0).Info("exec monitor unavailable; continuing without exec observation", "error", cerr.Error())
		}
	} else {
		log.Log.V(0).Info("exec monitor spec unavailable; continuing without exec observation", "error", eerr.Error())
	}

	return nil
}

func (m *Manager) AttachPrograms() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	// The syscall collection is required; network/file are best-effort and may be
	// nil in degraded mode. Guard against a misordered Start()/AttachPrograms().
	if m.syscallCollection == nil {
		return fmt.Errorf("cannot attach: eBPF programs not loaded (call LoadPrograms first)")
	}
	// Idempotent: if programs are already attached, do nothing. Start() calls this
	// too, so a caller doing LoadPrograms+AttachPrograms+Start must not double-attach.
	if len(m.syscallLinks) > 0 || len(m.fileLinks) > 0 || len(m.networkLinks) > 0 || len(m.execLinks) > 0 || len(m.capLinks) > 0 {
		return nil
	}

	// Attach the single raw tracepoint on sys_enter. One program observes every
	// syscall (vs a hand-picked handful of tracepoints), which is what the
	// learner needs; per-(cgroup,syscall) dedup happens in-kernel.
	if prog := m.syscallCollection.Programs["handle_sys_enter"]; prog != nil {
		l, err := link.AttachRawTracepoint(link.RawTracepointOptions{
			Name:    "sys_enter",
			Program: prog,
		})
		if err != nil {
			return fmt.Errorf("failed to attach raw_tracepoint sys_enter: %v", err)
		}
		m.syscallLinks = append(m.syscallLinks, l)
	}

	// Attach the file monitor via the BPF LSM file_open hook. This sees the
	// resolved struct file (full path via bpf_d_path) and, in a later phase, can
	// DENY by returning -EPERM - something tracepoints cannot do. Requires a
	// kernel booted with the bpf LSM active (lsm=...,bpf).
	if m.fileCollection != nil {
		if prog := m.fileCollection.Programs["file_open"]; prog != nil {
			l, err := link.AttachLSM(link.LSMOptions{Program: prog})
			if err != nil {
				// Degrade gracefully: without the bpf LSM active, keep running with
				// syscall observation rather than failing the whole data plane.
				log.Log.V(0).Info("lsm/file_open attach failed; file enforcement/observation disabled (enable with lsm=...,bpf)", "error", err.Error())
			} else {
				m.fileLinks = append(m.fileLinks, l)
			}
		}
	}

	// Attach the network monitor via the LSM socket_connect hook (best-effort).
	// LSM (vs a kprobe) lets us DENY unlearned egress in-kernel, mirroring files.
	if m.networkCollection != nil {
		if prog := m.networkCollection.Programs["socket_connect"]; prog != nil {
			l, err := link.AttachLSM(link.LSMOptions{Program: prog})
			if err != nil {
				log.Log.V(0).Info("lsm/socket_connect attach failed; network observation/enforcement disabled", "error", err.Error())
			} else {
				m.networkLinks = append(m.networkLinks, l)
			}
		}
	}

	// Attach the exec monitor via the LSM bprm_check_security hook (best-effort);
	// denies unlearned executables in enforce mode.
	if m.execCollection != nil {
		if prog := m.execCollection.Programs["bprm_check"]; prog != nil {
			l, err := link.AttachLSM(link.LSMOptions{Program: prog})
			if err != nil {
				log.Log.V(0).Info("lsm/bprm_check_security attach failed; exec observation/enforcement disabled", "error", err.Error())
			} else {
				m.execLinks = append(m.execLinks, l)
			}
		}
	}

	// Attach the capability monitor via the LSM capable hook (best-effort).
	if m.capCollection != nil {
		if prog := m.capCollection.Programs["capable_check"]; prog != nil {
			l, err := link.AttachLSM(link.LSMOptions{Program: prog})
			if err != nil {
				log.Log.V(0).Info("lsm/capable attach failed; capability observation disabled", "error", err.Error())
			} else {
				m.capLinks = append(m.capLinks, l)
			}
		}
	}

	// Setup event readers
	if err := m.setupEventReaders(); err != nil {
		return fmt.Errorf("failed to setup event readers: %v", err)
	}

	return nil
}

func (m *Manager) setupEventReaders() error {
	// Syscall events
	eventsMap := m.syscallCollection.Maps["events"]
	if eventsMap != nil {
		reader, err := ringbuf.NewReader(eventsMap)
		if err != nil {
			return fmt.Errorf("failed to create syscall event reader: %v", err)
		}
		m.eventReader = reader
	}

	// Network events (best-effort; nil in degraded mode).
	if m.networkCollection != nil {
		if networkEventsMap := m.networkCollection.Maps["network_events"]; networkEventsMap != nil {
			reader, err := ringbuf.NewReader(networkEventsMap)
			if err != nil {
				log.Log.V(0).Info("network event reader unavailable", "error", err.Error())
			} else {
				m.networkEventReader = reader
			}
		}
	}

	// File events (best-effort; nil in degraded mode).
	if m.fileCollection != nil {
		if fileEventsMap := m.fileCollection.Maps["file_events"]; fileEventsMap != nil {
			reader, err := ringbuf.NewReader(fileEventsMap)
			if err != nil {
				return fmt.Errorf("failed to create file event reader: %v", err)
			}
			m.fileEventReader = reader
		}
	}

	// Capability events (best-effort; nil in degraded mode).
	if m.capCollection != nil {
		if capEventsMap := m.capCollection.Maps["cap_events"]; capEventsMap != nil {
			reader, err := ringbuf.NewReader(capEventsMap)
			if err != nil {
				log.Log.V(0).Info("capability event reader unavailable", "error", err.Error())
			} else {
				m.capEventReader = reader
			}
		}
	}

	// Exec events (best-effort; nil in degraded mode).
	if m.execCollection != nil {
		if execEventsMap := m.execCollection.Maps["exec_events"]; execEventsMap != nil {
			reader, err := ringbuf.NewReader(execEventsMap)
			if err != nil {
				log.Log.V(0).Info("exec event reader unavailable", "error", err.Error())
			} else {
				m.execEventReader = reader
			}
		}
	}

	return nil
}

func (m *Manager) Start(ctx context.Context) error {
	m.mu.Lock()
	if m.running {
		m.mu.Unlock()
		return fmt.Errorf("manager is already running")
	}
	m.running = true
	m.mu.Unlock()

	// Attach programs
	if err := m.AttachPrograms(); err != nil {
		return fmt.Errorf("failed to attach programs: %v", err)
	}

	// Start event processing goroutines
	go m.processSyscallEvents(ctx)
	go m.processNetworkEvents(ctx)
	go m.processFileEvents(ctx)
	go m.processExecEvents(ctx)
	go m.processCapabilityEvents(ctx)

	return nil
}

func (m *Manager) Stop() {
	m.mu.Lock()
	defer m.mu.Unlock()

	if !m.running {
		return
	}

	close(m.stopCh)
	m.running = false

	// Close event readers
	if m.eventReader != nil {
		m.eventReader.Close()
	}
	if m.networkEventReader != nil {
		m.networkEventReader.Close()
	}
	if m.fileEventReader != nil {
		m.fileEventReader.Close()
	}

	// Detach all links
	for _, l := range m.syscallLinks {
		l.Close()
	}
	for _, l := range m.networkLinks {
		l.Close()
	}
	for _, l := range m.fileLinks {
		l.Close()
	}

	// Close collections
	if m.syscallCollection != nil {
		m.syscallCollection.Close()
	}
	if m.networkCollection != nil {
		m.networkCollection.Close()
	}
	if m.fileCollection != nil {
		m.fileCollection.Close()
	}
}

func (m *Manager) Close() {
	m.Stop()
}

func (m *Manager) AddEventHandler(handler EventHandler) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.eventHandlers = append(m.eventHandlers, handler)
}

// GetCapabilities returns the system capabilities detected during initialization
func (m *Manager) GetCapabilities() *SystemCapabilities {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.capabilities
}

// CheckCapabilities re-checks system capabilities
func (m *Manager) CheckCapabilities() (*SystemCapabilities, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	capabilities, err := m.capabilityChecker.CheckSystemCapabilities()
	if err != nil {
		return nil, err
	}
	m.capabilities = capabilities
	return capabilities, nil
}

func (m *Manager) UpdateContainerPolicy(containerID string, policy *ContainerPolicy) error {
	m.mu.RLock()
	defer m.mu.RUnlock()

	if m.syscallCollection == nil {
		return fmt.Errorf("syscall collection not loaded")
	}

	policyMap := m.syscallCollection.Maps["container_policies"]
	if policyMap == nil {
		return fmt.Errorf("container_policies map not found")
	}

	// Convert Go policy to eBPF format
	ebpfPolicy := convertToEBPFPolicy(policy)
	return policyMap.Put([]byte(containerID), ebpfPolicy)
}

func (m *Manager) UpdateNetworkPolicy(containerID string, policy *NetworkPolicy) error {
	m.mu.RLock()
	defer m.mu.RUnlock()

	if m.networkCollection == nil {
		return fmt.Errorf("network collection not loaded")
	}

	policyMap := m.networkCollection.Maps["network_policies"]
	if policyMap == nil {
		return fmt.Errorf("network_policies map not found")
	}

	// Convert Go policy to eBPF format
	ebpfPolicy := convertToEBPFNetworkPolicy(policy)
	return policyMap.Put([]byte(containerID), ebpfPolicy)
}

func (m *Manager) UpdateFilePolicy(containerID string, policy *FilePolicy) error {
	m.mu.RLock()
	defer m.mu.RUnlock()

	if m.fileCollection == nil {
		return fmt.Errorf("file collection not loaded")
	}

	policyMap := m.fileCollection.Maps["file_policies"]
	if policyMap == nil {
		return fmt.Errorf("file_policies map not found")
	}

	// Convert Go policy to eBPF format
	ebpfPolicy := convertToEBPFFilePolicy(policy)
	return policyMap.Put([]byte(containerID), ebpfPolicy)
}

// EventReader interface for reading events from eBPF programs
type EventReader interface {
	Read() (*EventRecord, error)
}

// EventRecord represents a raw event record from eBPF
type EventRecord struct {
	RawSample []byte
}

// processEvents handles event processing for different event types
func (m *Manager) processEvents(ctx context.Context, eventType string) {
	for {
		select {
		case <-ctx.Done():
			return
		case <-m.stopCh:
			return
		default:
			var rawSample []byte
			var err error

			switch eventType {
			case "syscall":
				if m.eventReader == nil {
					return
				}
				record, e := m.eventReader.Read()
				if e != nil {
					continue
				}
				rawSample = record.RawSample
				err = e
			case "network":
				if m.networkEventReader == nil {
					return
				}
				record, e := m.networkEventReader.Read()
				if e != nil {
					continue
				}
				rawSample = record.RawSample
				err = e
			case "file":
				if m.fileEventReader == nil {
					return
				}
				record, e := m.fileEventReader.Read()
				if e != nil {
					continue
				}
				rawSample = record.RawSample
				err = e
			case "capability":
				if m.capEventReader == nil {
					return
				}
				record, e := m.capEventReader.Read()
				if e != nil {
					continue
				}
				rawSample = record.RawSample
				err = e
			case "exec":
				if m.execEventReader == nil {
					return
				}
				record, e := m.execEventReader.Read()
				if e != nil {
					continue
				}
				rawSample = record.RawSample
				err = e
			default:
				return
			}

			if err != nil {
				continue
			}

			m.handleEventRecord(ctx, eventType, rawSample)
		}
	}
}

// handleEventRecord processes a single event record based on type.
//
// Every kind now counts its events, its denials, and its decode failures
// uniformly. Previously exec and capability records were counted only when
// denied, so an agent seeing exec traffic but denying none reported nothing at
// all, and undecodable records were dropped in complete silence.
func (m *Manager) handleEventRecord(ctx context.Context, eventType string, rawSample []byte) {
	switch eventType {
	case kindSyscall:
		event := parseSyscallEvent(rawSample)
		if event == nil {
			m.counters[kindSyscall].decodeErrors.Inc()
			return
		}
		m.counters[kindSyscall].events.Inc()
		if m.otelSyscallCounter != nil {
			m.otelSyscallCounter.Add(ctx, 1)
		}
		m.notifyHandlers(func(h EventHandler) { _ = h.HandleSyscallEvent(event) })
	case kindNetwork:
		event := parseNetworkEvent(rawSample)
		if event == nil {
			m.counters[kindNetwork].decodeErrors.Inc()
			return
		}
		m.counters[kindNetwork].events.Inc()
		if m.otelNetworkCounter != nil {
			m.otelNetworkCounter.Add(ctx, 1)
		}
		// Direction bit 0x80 marks an in-kernel denied connect (see network_monitor.c).
		if event.Direction&DeniedDirection != 0 {
			m.counters[kindNetwork].denials.Inc()
		}
		m.notifyHandlers(func(h EventHandler) { _ = h.HandleNetworkEvent(event) })
	case kindFile:
		event := parseFileEvent(rawSample)
		if event == nil {
			m.counters[kindFile].decodeErrors.Inc()
			return
		}
		m.counters[kindFile].events.Inc()
		if m.otelFileCounter != nil {
			m.otelFileCounter.Add(ctx, 1)
		}
		// Flag bit 0x80000000 marks an in-kernel denied open (see file_monitor.c).
		if event.Flags&DeniedFlag != 0 {
			m.counters[kindFile].denials.Inc()
		}
		m.notifyHandlers(func(h EventHandler) { _ = h.HandleFileEvent(event) })
	case kindCapability:
		event := parseCapabilityEvent(rawSample)
		if event == nil {
			m.counters[kindCapability].decodeErrors.Inc()
			return
		}
		m.counters[kindCapability].events.Inc()
		if event.Flags&DeniedFlag != 0 {
			m.counters[kindCapability].denials.Inc()
		}
		m.notifyHandlers(func(h EventHandler) { _ = h.HandleCapabilityEvent(event) })
	case kindExec:
		event := parseProcessEvent(rawSample)
		if event == nil {
			m.counters[kindExec].decodeErrors.Inc()
			return
		}
		m.counters[kindExec].events.Inc()
		// Flag bit 0x80000000 marks an in-kernel denied execve (see exec_monitor.c).
		if event.Flags&DeniedFlag != 0 {
			m.counters[kindExec].denials.Inc()
		}
		m.notifyHandlers(func(h EventHandler) { _ = h.HandleProcessEvent(event) })
	}
}

// notifyHandlers safely notifies all event handlers
func (m *Manager) notifyHandlers(notify func(EventHandler)) {
	m.mu.RLock()
	handlers := make([]EventHandler, len(m.eventHandlers))
	copy(handlers, m.eventHandlers)
	m.mu.RUnlock()

	// Dispatch synchronously. This used to spawn a goroutine per handler per
	// event, which cost a scheduler round-trip and an allocation on every
	// record - the dominant cost in the pipeline at any real event rate - and
	// delivered events out of order, so a handler could observe an exec after
	// the profile it belonged to had already been reconciled.
	//
	// The tradeoff is that a slow handler now stalls the ring-buffer reader.
	// That is the correct place for the decision: handlers that can block own a
	// bounded queue and drop under pressure (see pkg/export.NewQueue), which
	// makes the loss explicit and countable instead of silently unbounding
	// memory in a goroutine pile-up.
	for _, handler := range handlers {
		notify(handler)
	}
}

// Wrapper functions for backward compatibility
func (m *Manager) processSyscallEvents(ctx context.Context) {
	m.processEvents(ctx, "syscall")
}

func (m *Manager) processNetworkEvents(ctx context.Context) {
	m.processEvents(ctx, "network")
}

func (m *Manager) processFileEvents(ctx context.Context) {
	m.processEvents(ctx, "file")
}

func (m *Manager) processExecEvents(ctx context.Context) {
	m.processEvents(ctx, "exec")
}

func (m *Manager) processCapabilityEvents(ctx context.Context) {
	m.processEvents(ctx, "capability")
}

// Helper functions for converting between Go and eBPF data structures

// EBPFContainerPolicy represents the eBPF container_policy struct layout
type EBPFContainerPolicy struct {
	ContainerID     uint32     // container_id
	LearningMode    uint32     // learning_mode (1 = learning, 0 = enforcement)
	AllowedSyscalls [64]uint64 // allowed_syscalls bitmap for syscalls 0-4095
	ViolationCount  uint32     // violation_count
	LastUpdateNs    uint64     // last_update_ns
}

func convertToEBPFPolicy(policy *ContainerPolicy) *EBPFContainerPolicy {
	ebpfPolicy := &EBPFContainerPolicy{
		ContainerID:    0, // Will be set by caller as map key
		LearningMode:   0, // 0 = enforcement mode by default
		ViolationCount: 0,
		LastUpdateNs:   uint64(policy.LastUpdate.UnixNano()),
	}

	// Convert enforcement mode
	if policy.EnforcementMode == 0 { // Assuming 0 = monitoring/learning
		ebpfPolicy.LearningMode = 1
	}

	// Convert syscall map to bitmap
	for syscallNr, allowed := range policy.AllowedSyscalls {
		if allowed && syscallNr < 4096 { // eBPF supports 0-4095
			wordIdx := syscallNr / 64
			bitIdx := syscallNr % 64
			if wordIdx < 64 {
				ebpfPolicy.AllowedSyscalls[wordIdx] |= (1 << bitIdx)
			}
		}
	}

	return ebpfPolicy
}

// EBPFConnectionPolicy represents the eBPF connection_policy struct layout
type EBPFConnectionPolicy struct {
	ContainerID         uint32      // container_id
	AllowedDestinations [256]uint32 // allowed_destinations (IP addresses)
	AllowedPorts        [64]uint16  // allowed_ports
	LearningMode        uint32      // learning_mode (1 = learning, 0 = enforcement)
	LastUpdateNs        uint64      // last_update_ns
}

func convertToEBPFNetworkPolicy(policy *NetworkPolicy) *EBPFConnectionPolicy {
	ebpfPolicy := &EBPFConnectionPolicy{
		ContainerID:  0, // Will be set by caller as map key
		LearningMode: 0, // 0 = enforcement mode by default
		LastUpdateNs: uint64(policy.LastUpdate.UnixNano()),
	}

	// Convert enforcement mode
	if policy.EnforcementMode == 0 { // Assuming 0 = monitoring/learning
		ebpfPolicy.LearningMode = 1
	}

	// Convert allowed IPs (both egress and ingress)
	destIdx := 0
	for _, ip := range policy.AllowedEgressIPs {
		if destIdx < 256 {
			ebpfPolicy.AllowedDestinations[destIdx] = ip
			destIdx++
		}
	}
	for _, ip := range policy.AllowedIngressIPs {
		if destIdx < 256 {
			ebpfPolicy.AllowedDestinations[destIdx] = ip
			destIdx++
		}
	}

	// Convert allowed ports (both egress and ingress)
	portIdx := 0
	for port := range policy.AllowedEgressPorts {
		if portIdx < 64 {
			ebpfPolicy.AllowedPorts[portIdx] = port
			portIdx++
		}
	}
	for port := range policy.AllowedIngressPorts {
		if portIdx < 64 {
			ebpfPolicy.AllowedPorts[portIdx] = port
			portIdx++
		}
	}

	return ebpfPolicy
}

// EBPFFileAccessPolicy represents the eBPF file_access_policy struct layout
type EBPFFileAccessPolicy struct {
	ContainerID  uint32         // container_id
	LearningMode uint32         // learning_mode (1 = learning, 0 = enforcement)
	AllowedPaths [1024][64]byte // allowed_paths (char array)
	PathCount    uint32         // path_count (number of valid paths)
	LastUpdateNs uint64         // last_update_ns
}

func convertToEBPFFilePolicy(policy *FilePolicy) *EBPFFileAccessPolicy {
	ebpfPolicy := &EBPFFileAccessPolicy{
		ContainerID:  0, // Will be set by caller as map key
		LearningMode: 0, // 0 = enforcement mode by default
		PathCount:    0,
		LastUpdateNs: uint64(policy.LastUpdate.UnixNano()),
	}

	// Convert enforcement mode
	if policy.EnforcementMode == 0 { // Assuming 0 = monitoring/learning
		ebpfPolicy.LearningMode = 1
	}

	// Convert allowed paths to fixed-size char arrays
	for i, path := range policy.AllowedPaths {
		if i >= 1024 { // eBPF limit
			break
		}

		// Copy path to fixed-size array (max 63 chars + null terminator)
		pathBytes := []byte(path)
		copyLen := len(pathBytes)
		if copyLen >= 64 {
			copyLen = 63 // Leave space for null terminator
		}

		copy(ebpfPolicy.AllowedPaths[i][:copyLen], pathBytes)
		ebpfPolicy.AllowedPaths[i][copyLen] = 0 // Null terminator
		ebpfPolicy.PathCount++
	}

	return ebpfPolicy
}

// parseSyscallEvent decodes the CO-RE `struct syscall_event` emitted by
// bpf/syscall_monitor.c (see that file for the authoritative layout):
//
//	__u64 cgroup_id; __u64 timestamp_ns; __u64 syscall_nr;
//	__u32 pid; __u32 tid; __u32 uid; __u32 gid; __u8 comm[16];  // 56 bytes
func parseSyscallEvent(data []byte) *SyscallEvent {
	const size = 8 + 8 + 8 + 4 + 4 + 4 + 4 + 16 // 56
	if len(data) < size {
		return nil
	}

	event := &SyscallEvent{
		CgroupID:  binary.LittleEndian.Uint64(data[0:8]),
		Timestamp: binary.LittleEndian.Uint64(data[8:16]),
		SyscallNr: binary.LittleEndian.Uint64(data[16:24]),
		PID:       binary.LittleEndian.Uint32(data[24:28]),
		UID:       binary.LittleEndian.Uint32(data[32:36]),
		GID:       binary.LittleEndian.Uint32(data[36:40]),
	}
	// eBPF `pid` is the userspace TGID; expose it as both for now.
	event.TGID = event.PID

	comm := data[40:56]
	if i := indexZero(comm); i >= 0 {
		comm = comm[:i]
	}
	event.Comm = string(comm)

	// Until pod attribution (pkg/attribution) resolves cgroup->pod, surface the
	// cgroup id as the container identifier.
	event.ContainerID = fmt.Sprintf("cgroup:%d", event.CgroupID)

	return event
}

func indexZero(b []byte) int {
	for i, c := range b {
		if c == 0 {
			return i
		}
	}
	return -1
}

func parseNetworkEvent(data []byte) *NetworkEvent {
	// CO-RE `struct network_event` from bpf/network_monitor.c:
	//   __u64 cgroup_id; __u64 timestamp_ns; __u32 pid; __u32 saddr; __u32 daddr;
	//   __u16 sport; __u16 dport; __u8 protocol; __u8 direction; __u8 family;
	//   __u8 pad; __u8 daddr6[16]; __u8 comm[16];   // 72 bytes
	const size = 8 + 8 + 4 + 4 + 4 + 2 + 2 + 1 + 1 + 1 + 1 + 16 + 16
	if len(data) < size {
		return nil
	}
	event := &NetworkEvent{
		CgroupID:  binary.LittleEndian.Uint64(data[0:8]),
		Timestamp: binary.LittleEndian.Uint64(data[8:16]),
		PID:       binary.LittleEndian.Uint32(data[16:20]),
		SrcIP:     binary.LittleEndian.Uint32(data[20:24]),
		DstIP:     binary.LittleEndian.Uint32(data[24:28]),
		SrcPort:   binary.LittleEndian.Uint16(data[28:30]),
		DstPort:   binary.LittleEndian.Uint16(data[30:32]),
		Protocol:  data[32],
		Direction: data[33],
		Family:    data[34],
	}
	copy(event.DstIP6[:], data[36:52])
	comm := data[52:68]
	if i := indexZero(comm); i >= 0 {
		comm = comm[:i]
	}
	event.Comm = string(comm)
	event.TGID = event.PID
	event.ContainerID = fmt.Sprintf("cgroup:%d", event.CgroupID)
	return event
}

// DestinationString renders the event destination for either address family.
func (e *NetworkEvent) DestinationString() string {
	if e.Family == 10 { // AF_INET6
		ip := net.IP(e.DstIP6[:])
		return fmt.Sprintf("[%s]:%d", ip.String(), e.DstPort)
	}
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], e.DstIP)
	return fmt.Sprintf("%s:%d", net.IP(b[:]).String(), e.DstPort)
}

func parseFileEvent(data []byte) *FileEvent {
	// CO-RE `struct file_event` from bpf/file_monitor.c:
	//   __u64 cgroup_id; __u64 timestamp_ns; __u32 pid; __u32 uid; __u32 gid;
	//   __u32 flags; __u8 comm[16]; __u8 path[128];   // 176 bytes
	const size = 8 + 8 + 4 + 4 + 4 + 4 + 16 + 128
	if len(data) < size {
		return nil
	}
	event := &FileEvent{
		CgroupID:  binary.LittleEndian.Uint64(data[0:8]),
		Timestamp: binary.LittleEndian.Uint64(data[8:16]),
		PID:       binary.LittleEndian.Uint32(data[16:20]),
		UID:       binary.LittleEndian.Uint32(data[20:24]),
		GID:       binary.LittleEndian.Uint32(data[24:28]),
		Flags:     binary.LittleEndian.Uint32(data[28:32]),
	}
	event.TGID = event.PID
	comm := data[32:48]
	if i := indexZero(comm); i >= 0 {
		comm = comm[:i]
	}
	event.Comm = string(comm)
	path := data[48:176]
	if i := indexZero(path); i >= 0 {
		path = path[:i]
	}
	event.Path = string(path)
	event.ContainerID = fmt.Sprintf("cgroup:%d", event.CgroupID)
	return event
}

// Validation methods for policy types
func (cp *ContainerPolicy) Validate() error {
	if cp.AllowedSyscalls == nil {
		return fmt.Errorf("allowed syscalls map cannot be nil")
	}
	if cp.EnforcementMode > 3 {
		return fmt.Errorf("invalid enforcement mode: %d", cp.EnforcementMode)
	}
	return nil
}

func (np *NetworkPolicy) Validate() error {
	if np.AllowedEgressPorts == nil || np.AllowedIngressPorts == nil {
		return fmt.Errorf("port maps cannot be nil")
	}
	if np.EnforcementMode > 3 {
		return fmt.Errorf("invalid enforcement mode: %d", np.EnforcementMode)
	}
	return nil
}

func (fp *FilePolicy) Validate() error {
	if fp.EnforcementMode > 3 {
		return fmt.Errorf("invalid enforcement mode: %d", fp.EnforcementMode)
	}
	return nil
}

// FnvPathHash computes the FNV-1a hash that bpf/file_monitor.c uses to key its
// in-kernel file block list. Userspace inserts this hash into the file_blocked
// map to DENY opens of the given path in-kernel.
func FnvPathHash(path string) uint64 {
	var h uint64 = 1469598103934665603
	for i := 0; i < len(path); i++ {
		h ^= uint64(path[i])
		h *= 1099511628211
	}
	return h
}

// SetFileEnforcement flips a cgroup between learning and enforcing for the file
// allow-list. In enforcing mode, opens of paths not in the learned allow-set are
// denied in-kernel. Absent from the mode map == learning (the default).
func (m *Manager) SetFileEnforcement(cgroupID uint64, enforce bool) error {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.fileCollection == nil {
		return fmt.Errorf("file monitor not loaded (bpf LSM unavailable?)")
	}
	fm := m.fileCollection.Maps["file_mode"]
	if fm == nil {
		return fmt.Errorf("file_mode map not found")
	}
	if enforce {
		return fm.Put(cgroupID, uint8(1))
	}
	// Learning: remove the entry so the default (learn) applies. Ignore ENOENT.
	_ = fm.Delete(cgroupID)
	return nil
}

// LearnedFileCount returns the number of (cgroup,path) entries currently in the
// file allow-set (diagnostics / profile sizing). Returns 0 if unavailable.
func (m *Manager) LearnedFileCount() int {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.fileCollection == nil {
		return 0
	}
	fm := m.fileCollection.Maps["file_allowed"]
	if fm == nil {
		return 0
	}
	var k uint64
	var v uint8
	n := 0
	it := fm.Iterate()
	for it.Next(&k, &v) {
		n++
	}
	return n
}

// SetNetworkEnforcement flips a cgroup between learning and enforcing for the
// network destination allow-list. In enforcing mode, connect() to a destination
// not in the learned allow-set is denied in-kernel.
func (m *Manager) SetNetworkEnforcement(cgroupID uint64, enforce bool) error {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.networkCollection == nil {
		return fmt.Errorf("network monitor not loaded (bpf LSM unavailable?)")
	}
	nm := m.networkCollection.Maps["network_mode"]
	if nm == nil {
		return fmt.Errorf("network_mode map not found")
	}
	if enforce {
		return nm.Put(cgroupID, uint8(1))
	}
	_ = nm.Delete(cgroupID)
	return nil
}

// parseProcessEvent decodes the CO-RE `struct exec_event` from bpf/exec_monitor.c:
//
//	__u64 cgroup_id; __u64 timestamp_ns; __u32 pid; __u32 ppid; __u32 uid;
//	__u32 flags; __u8 comm[16]; __u8 pcomm[16]; __u8 filename[128];  // 192 bytes
func parseProcessEvent(data []byte) *ProcessEvent {
	const size = 8 + 8 + 4 + 4 + 4 + 4 + 16 + 16 + 128
	if len(data) < size {
		return nil
	}
	ev := &ProcessEvent{
		CgroupID:  binary.LittleEndian.Uint64(data[0:8]),
		Timestamp: binary.LittleEndian.Uint64(data[8:16]),
		PID:       binary.LittleEndian.Uint32(data[16:20]),
		PPID:      binary.LittleEndian.Uint32(data[20:24]),
		UID:       binary.LittleEndian.Uint32(data[24:28]),
		Flags:     binary.LittleEndian.Uint32(data[28:32]),
	}
	cut := func(b []byte) string {
		if i := indexZero(b); i >= 0 {
			b = b[:i]
		}
		return string(b)
	}
	ev.Comm = cut(data[32:48])
	ev.ParentComm = cut(data[48:64])
	ev.Filename = cut(data[64:192])
	ev.ContainerID = fmt.Sprintf("cgroup:%d", ev.CgroupID)
	return ev
}

// SetExecEnforcement flips a cgroup between learning and enforcing for the exec
// allow-list. In enforcing mode, execve of a binary not in the learned set is
// denied in-kernel.
func (m *Manager) SetExecEnforcement(cgroupID uint64, enforce bool) error {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.execCollection == nil {
		return fmt.Errorf("exec monitor not loaded (bpf LSM unavailable?)")
	}
	em := m.execCollection.Maps["exec_mode"]
	if em == nil {
		return fmt.Errorf("exec_mode map not found")
	}
	if enforce {
		return em.Put(cgroupID, uint8(1))
	}
	_ = em.Delete(cgroupID)
	return nil
}

// MapSizing overrides the max_entries of the learned-state BPF maps at load
// time. The compiled defaults are sized for a typical node; dense nodes (many
// pods, many distinct paths) can raise them, and small edge nodes can lower
// them. Zero means "keep the compiled default".
//
// These maps are preallocated by the kernel, so the values directly determine
// the agent's resident memory: an LRU hash costs roughly 60 bytes per entry.
type MapSizing struct {
	FileAllowed    uint32 // (cgroup, path) allow-set
	NetworkAllowed uint32 // (cgroup, dst) allow-set
	ExecAllowed    uint32 // (cgroup, binary) allow-set
	SyscallSeen    uint32 // (cgroup, syscall) dedup
	RingBufBytes   uint32 // per-program ring buffer size in bytes
}

// applyMapSizing rewrites max_entries on a loaded CollectionSpec before the maps
// are created in the kernel.
func applyMapSizing(spec *ebpf.CollectionSpec, sizes map[string]uint32) {
	if spec == nil {
		return
	}
	for name, n := range sizes {
		if n == 0 {
			continue
		}
		if m, ok := spec.Maps[name]; ok && m != nil {
			m.MaxEntries = n
		}
	}
}

// SetMapSizing configures the overrides applied by the next LoadPrograms call.
func (m *Manager) SetMapSizing(s MapSizing) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.mapSizing = s
}

// parseCapabilityEvent decodes `struct cap_event` from bpf/capability_monitor.c:
//
//	__u64 cgroup_id; __u64 timestamp_ns; __u32 pid; __u32 cap; __u32 flags;
//	__u8 comm[16];   // 44 bytes
func parseCapabilityEvent(data []byte) *CapabilityEvent {
	const size = 8 + 8 + 4 + 4 + 4 + 16
	if len(data) < size {
		return nil
	}
	ev := &CapabilityEvent{
		CgroupID:   binary.LittleEndian.Uint64(data[0:8]),
		Timestamp:  binary.LittleEndian.Uint64(data[8:16]),
		PID:        binary.LittleEndian.Uint32(data[16:20]),
		Capability: binary.LittleEndian.Uint32(data[20:24]),
		Flags:      binary.LittleEndian.Uint32(data[24:28]),
	}
	comm := data[28:44]
	if i := indexZero(comm); i >= 0 {
		comm = comm[:i]
	}
	ev.Comm = string(comm)
	ev.ContainerID = fmt.Sprintf("cgroup:%d", ev.CgroupID)
	return ev
}

// SetCapabilityEnforcement flips a cgroup between learning and enforcing for the
// capability allow-list. Under enforcement a capability the workload never used
// during learning is denied with -EPERM.
func (m *Manager) SetCapabilityEnforcement(cgroupID uint64, enforce bool) error {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.capCollection == nil {
		return fmt.Errorf("capability monitor not loaded (bpf LSM unavailable?)")
	}
	cm := m.capCollection.Maps["cap_mode"]
	if cm == nil {
		return fmt.Errorf("cap_mode map not found")
	}
	if enforce {
		return cm.Put(cgroupID, uint8(1))
	}
	_ = cm.Delete(cgroupID)
	return nil
}

// CapabilityName renders a Linux capability number as its canonical name.
func CapabilityName(c uint32) string {
	if int(c) < len(capabilityNames) {
		return capabilityNames[c]
	}
	return fmt.Sprintf("CAP_%d", c)
}

var capabilityNames = []string{
	"CAP_CHOWN", "CAP_DAC_OVERRIDE", "CAP_DAC_READ_SEARCH", "CAP_FOWNER", "CAP_FSETID",
	"CAP_KILL", "CAP_SETGID", "CAP_SETUID", "CAP_SETPCAP", "CAP_LINUX_IMMUTABLE",
	"CAP_NET_BIND_SERVICE", "CAP_NET_BROADCAST", "CAP_NET_ADMIN", "CAP_NET_RAW",
	"CAP_IPC_LOCK", "CAP_IPC_OWNER", "CAP_SYS_MODULE", "CAP_SYS_RAWIO", "CAP_SYS_CHROOT",
	"CAP_SYS_PTRACE", "CAP_SYS_PACCT", "CAP_SYS_ADMIN", "CAP_SYS_BOOT", "CAP_SYS_NICE",
	"CAP_SYS_RESOURCE", "CAP_SYS_TIME", "CAP_SYS_TTY_CONFIG", "CAP_MKNOD", "CAP_LEASE",
	"CAP_AUDIT_WRITE", "CAP_AUDIT_CONTROL", "CAP_SETFCAP", "CAP_MAC_OVERRIDE",
	"CAP_MAC_ADMIN", "CAP_SYSLOG", "CAP_WAKE_ALARM", "CAP_BLOCK_SUSPEND", "CAP_AUDIT_READ",
	"CAP_PERFMON", "CAP_BPF", "CAP_CHECKPOINT_RESTORE",
}
