// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNetworkMonitor returns the embedded CollectionSpec for NetworkMonitor.
func LoadNetworkMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetworkMonitor: %w", err)
	}

	return spec, err
}

// LoadNetworkMonitorObjects loads NetworkMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkMonitorObjects
//	*NetworkMonitorPrograms
//	*NetworkMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetworkMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorSpecs struct {
	NetworkMonitorProgramSpecs
	NetworkMonitorMapSpecs
	NetworkMonitorVariableSpecs
}

// NetworkMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorProgramSpecs struct {
	SocketConnect *ebpf.ProgramSpec `ebpf:"socket_connect"`
}

// NetworkMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorMapSpecs struct {
	NetworkAllowed *ebpf.MapSpec `ebpf:"network_allowed"`
	NetworkEvents  *ebpf.MapSpec `ebpf:"network_events"`
	NetworkMode    *ebpf.MapSpec `ebpf:"network_mode"`
}

// NetworkMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMonitorVariableSpecs struct {
}

// NetworkMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorObjects struct {
	NetworkMonitorPrograms
	NetworkMonitorMaps
	NetworkMonitorVariables
}

func (o *NetworkMonitorObjects) Close() error {
	return _NetworkMonitorClose(
		&o.NetworkMonitorPrograms,
		&o.NetworkMonitorMaps,
	)
}

// NetworkMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorMaps struct {
	NetworkAllowed *ebpf.Map `ebpf:"network_allowed"`
	NetworkEvents  *ebpf.Map `ebpf:"network_events"`
	NetworkMode    *ebpf.Map `ebpf:"network_mode"`
}

func (m *NetworkMonitorMaps) Close() error {
	return _NetworkMonitorClose(
		m.NetworkAllowed,
		m.NetworkEvents,
		m.NetworkMode,
	)
}

// NetworkMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorVariables struct {
}

// NetworkMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMonitorPrograms struct {
	SocketConnect *ebpf.Program `ebpf:"socket_connect"`
}

func (p *NetworkMonitorPrograms) Close() error {
	return _NetworkMonitorClose(
		p.SocketConnect,
	)
}

func _NetworkMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networkmonitor_bpfel.o
var _NetworkMonitorBytes []byte
