// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type ShellMonitorShellEvent struct {
	_           structs.HostLayout
	CgroupId    uint64
	TimestampNs uint64
	Pid         uint32
	Tid         uint32
	Uid         uint32
	Flags       uint32
	Comm        [16]uint8
	Line        [232]uint8
}

// LoadShellMonitor returns the embedded CollectionSpec for ShellMonitor.
func LoadShellMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ShellMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ShellMonitor: %w", err)
	}

	return spec, err
}

// LoadShellMonitorObjects loads ShellMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ShellMonitorObjects
//	*ShellMonitorPrograms
//	*ShellMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadShellMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadShellMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ShellMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ShellMonitorSpecs struct {
	ShellMonitorProgramSpecs
	ShellMonitorMapSpecs
	ShellMonitorVariableSpecs
}

// ShellMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ShellMonitorProgramSpecs struct {
	HandleReadline *ebpf.ProgramSpec `ebpf:"handle_readline"`
}

// ShellMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ShellMonitorMapSpecs struct {
	ShellConfig  *ebpf.MapSpec `ebpf:"shell_config"`
	ShellEvents  *ebpf.MapSpec `ebpf:"shell_events"`
	ShellScratch *ebpf.MapSpec `ebpf:"shell_scratch"`
}

// ShellMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ShellMonitorVariableSpecs struct {
}

// ShellMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadShellMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ShellMonitorObjects struct {
	ShellMonitorPrograms
	ShellMonitorMaps
	ShellMonitorVariables
}

func (o *ShellMonitorObjects) Close() error {
	return _ShellMonitorClose(
		&o.ShellMonitorPrograms,
		&o.ShellMonitorMaps,
	)
}

// ShellMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadShellMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ShellMonitorMaps struct {
	ShellConfig  *ebpf.Map `ebpf:"shell_config"`
	ShellEvents  *ebpf.Map `ebpf:"shell_events"`
	ShellScratch *ebpf.Map `ebpf:"shell_scratch"`
}

func (m *ShellMonitorMaps) Close() error {
	return _ShellMonitorClose(
		m.ShellConfig,
		m.ShellEvents,
		m.ShellScratch,
	)
}

// ShellMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadShellMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ShellMonitorVariables struct {
}

// ShellMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadShellMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type ShellMonitorPrograms struct {
	HandleReadline *ebpf.Program `ebpf:"handle_readline"`
}

func (p *ShellMonitorPrograms) Close() error {
	return _ShellMonitorClose(
		p.HandleReadline,
	)
}

func _ShellMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed shellmonitor_arm64_bpfel.o
var _ShellMonitorBytes []byte
