// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SyscallMonitorConfig struct {
	_        structs.HostLayout
	Disabled uint8
}

// LoadSyscallMonitor returns the embedded CollectionSpec for SyscallMonitor.
func LoadSyscallMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SyscallMonitor: %w", err)
	}

	return spec, err
}

// LoadSyscallMonitorObjects loads SyscallMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SyscallMonitorObjects
//	*SyscallMonitorPrograms
//	*SyscallMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSyscallMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSyscallMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SyscallMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallMonitorSpecs struct {
	SyscallMonitorProgramSpecs
	SyscallMonitorMapSpecs
	SyscallMonitorVariableSpecs
}

// SyscallMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallMonitorProgramSpecs struct {
	HandleSysEnter *ebpf.ProgramSpec `ebpf:"handle_sys_enter"`
}

// SyscallMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallMonitorMapSpecs struct {
	ConfigMap   *ebpf.MapSpec `ebpf:"config_map"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	SyscallSeen *ebpf.MapSpec `ebpf:"syscall_seen"`
}

// SyscallMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallMonitorVariableSpecs struct {
}

// SyscallMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallMonitorObjects struct {
	SyscallMonitorPrograms
	SyscallMonitorMaps
	SyscallMonitorVariables
}

func (o *SyscallMonitorObjects) Close() error {
	return _SyscallMonitorClose(
		&o.SyscallMonitorPrograms,
		&o.SyscallMonitorMaps,
	)
}

// SyscallMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallMonitorMaps struct {
	ConfigMap   *ebpf.Map `ebpf:"config_map"`
	Events      *ebpf.Map `ebpf:"events"`
	SyscallSeen *ebpf.Map `ebpf:"syscall_seen"`
}

func (m *SyscallMonitorMaps) Close() error {
	return _SyscallMonitorClose(
		m.ConfigMap,
		m.Events,
		m.SyscallSeen,
	)
}

// SyscallMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallMonitorVariables struct {
}

// SyscallMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallMonitorPrograms struct {
	HandleSysEnter *ebpf.Program `ebpf:"handle_sys_enter"`
}

func (p *SyscallMonitorPrograms) Close() error {
	return _SyscallMonitorClose(
		p.HandleSysEnter,
	)
}

func _SyscallMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscallmonitor_bpfeb.o
var _SyscallMonitorBytes []byte
