name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'

jobs:
  lint-docs:
    name: Lint Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint Markdown files
      uses: articulate/actions-markdownlint@v1
      with:
        config: .markdownlint.yml
        files: '**/*.md'
        ignore: 'node_modules'

    - name: Check links in documentation
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.markdown-link-check.json'

  generate-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"

    - name: Install controller-gen
      run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest

    - name: Generate CRD documentation
      run: |
        mkdir -p docs/api
        controller-gen crd:crdVersions=v1 paths="./pkg/apis/..." output:crd:artifacts:config=docs/api/

    - name: Generate Go documentation
      run: |
        go install golang.org/x/tools/cmd/godoc@latest
        mkdir -p docs/go
        godoc -html > docs/go/index.html

    - name: Commit generated docs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git diff --staged --quiet || git commit -m "Auto-generate documentation"
        git push

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint-docs, generate-docs]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install -g @vuepress/cli
        npm install

    - name: Build documentation site
      run: |
        # Create a simple documentation site structure
        mkdir -p site/docs
        cp README.md site/docs/
        cp -r docs/* site/docs/ 2>/dev/null || true

        # Create a basic index
        cat > site/docs/README.md << 'EOF'
        # Pahlevan Documentation

        Welcome to the Pahlevan eBPF-based Kubernetes Security Operator documentation.

        ## Quick Links

        - [Getting Started](../README.md)
        - [API Reference](api/)
        - [Go Documentation](go/)

        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/docs
        destination_dir: docs